### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by robrobinbin** [SimpleMobileTools/General-Discussion#1]
# The current icons

**Pro**

* Similar icons: clearly one project, easy to recognize
* Stand out
* Simple icons for simple apps

**Cons**

*  Icons are so similar it might be confusing
* Not modern, outdated look
* Doesn't fit in
* They are orange

# Proposal

Maybe use icons from an icon theme. I propose Moka ([Desktop theme](https://github.com/snwh/moka-icon-theme)) or Numix ([Desktop theme](https://github.com/numixproject/numix-icon-theme-circle), [Android theme](https://github.com/numixproject/com.numix.icons_circle)).

Moka has a similar shape to the current theme, but more colorful.

Numix looks more modern and more like other Android icons. It provides a huge collection of different icons.

Both themes have (often multiple) icons that could be used for your apps. They are both under Creative Commons licenses, so simply add attribution on the "About" pages.

**Comment by tibbi** [comment]
I like the orange and the icons, will just make them flat :) Maybe if combined with #2 and changing launcher names, it will be not that confusing as they will be spread around.

**Comment by tibbi** [comment]
Im already updating apps with new icons which will be flat, and a bit smaller. I like them, so they will stay for a while. https://github.com/SimpleMobileTools/Simple-Camera/commit/a43d82d8a0779ba41ec13d745c60c9d0326b37d9
