### ISSUE TITLE
Allow applying the picked colors to all apps

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/General-Discussion#10]
With some button "Apply colors to all Simple Mobile Tools apps" at the customizing screen, or so.

**Comment by mueller-ma** [comment]
@tibbi In my opinion the old "dark theme switch" was better. It was a much easier way to change the colors to dark. Now I have to adjust 3 colors to get a nice dark theme

**Comment by tibbi** [comment]
many people want to change the orange color too. I will add some presets later like Light Theme, Dark Theme and maybe some other nice themes.

**Comment by tibbi** [comment]
will be added in 3.0.0
