### ISSUE TITLE
generic SDcard access / write permission error

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/General-Discussion#101]
Nokia 6, android 7.1.2,  Simple Notes and Simple Contacts.

After upgrading to the Pro versions i want to move my notes and contacts from the 5.x to the 6.x version. Pro and non-pro versions are installed. The problem is that when i want to export notes or contacts, i can not do it to the SDcard. Internal Storage works fine so i used that already to move my data.

-Simple Notes just exports silently, no "exported successfully" message, no error and no file created.
-Simple Contacts shows java.io.FileNotFoundException: [path/to/file.vcf] (Permission denied)
-Pro and non pro version behave the same. All versions and apps did ask to confirm the SDCARD permission as explained in a popup, which i did.

Is there any way I can provide more information and help to debug this?

**Comment by tibbi** [comment]
Contacts will work fine from version 6.1.0 released soon

**Comment by GuitarBilly** [comment]
Looking forward to it. 

Will Simple Notes also be fixed by a software update?

**Comment by tibbi** [comment]
if I will be able to reproduce it, then ye

**Comment by tibbi** [comment]
should be fixed already

**Comment by GuitarBilly** [comment]
yes, export to SD confirmed to work for Simple Notes v6.1.2 on Nokia 6, android 7.1.2
