### ISSUE TITLE
Can the "commons" lib be published on a F-Droid approved maven repo

### ISSUE THREAD

**Issue by licaon-kter** [SimpleMobileTools/General-Discussion#102]
...like jitpack.io or jcenter.bintray.com or [whatever](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L99) ?

**Comment by tibbi** [comment]
like the previous version 5.8.x? I broke something accidentally so "maven { url "https://dl.bintray.com/simplelibraries/commons" }" has to be added in the project build.gradle now

**Comment by licaon-kter** [comment]
I don't know the history of this.

Just saying that I'll have to disable the builds and/or autoupdates and/or downgrade the lib and hope it works.

**Comment by tibbi** [comment]
should be working fine again from commons 5.9.16+
