### ISSUE TITLE
Searching for a new italian translator

### ISSUE THREAD

**Issue by ema-pe** [SimpleMobileTools/General-Discussion#104]
Hi!

I'm working to translate these applications from November, if I recall correctly. I use Simple Calendar every day and it is really a fantastic application, also other apps are no less.

In these and future weeks I don't have time to follow the translation status, so I'm dropping as Italian translator. I'll continue to contribute closely until **20 April 2019**, after this date maybe I will contribute sporadically, but I won't follow the status anymore.

I opened this issue to inform @tibbi, In this month I'll try to find someone that can follow these applications, but I can't guarantee anything.

Thanks @tibbi for developing these applications, they are very useful.

Have a good day!
Emanuele

**Comment by tibbi** [comment]
Hey, thanks for the help :) Translators are coming and going, maybe there wont be anyone until you return, maybe there will. We will see.

**Comment by comradekingu** [comment]
Now easier than ever
https://hosted.weblate.org/languages/it/simple-mobile-tools/
or https://hosted.weblate.org/zen/simple-mobile-tools/-/it/?q=state:%3Ctranslated for anything that needs work
