### ISSUE TITLE
values-cy.xml:349: error: unescaped apostrophe in string 

### ISSUE THREAD

**Issue by 979451341** [SimpleMobileTools/General-Discussion#106]
"S\'mae<br><br>
              Gobeithio dy fod yn mwynhau\'r ap. Nid yw\'n cynnwys unrhyw hysbysebion, felly a fyddi di mor garedig 芒 chefnogi ei ddatblygiad gan brynu ap <a href="https://play.google.com/store/apps/details?id=com.simplemobiletools.thankyou">Simple Thank You</a>. Mi fydd hefyd yn stopio'r neges hon ymddangos eto.<br><br>
              Diolch!".

**Comment by tibbi** [comment]
thanks, fixed
