### ISSUE TITLE
values-cy.xml:498: error: unescaped apostrophe in string

### ISSUE THREAD

**Issue by judeGhenon** [SimpleMobileTools/General-Discussion#109]
Hi,
something goes wrong with apostrophe in the values again.
I'm using the com.simplemobiletools:commons:5.12.11.

Thanks for your support

**Comment by tibbi** [comment]
which app are you talking about?

**Comment by judeGhenon** [comment]
Hi,
thanks for your reply.
I'm talking about SimpleMobileTools-Calculator app.
I tried to progressively switch the commons lib version in my gradle file, but I always get that error and I am not able to build the app.

**Comment by tibbi** [comment]
okay, fixed it
