### ISSUE TITLE
If you don't mind me asking

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/General-Discussion#11]
Are you being paid to write these apps? If not, how can you afford to spend so much time on them?

I ask because I'm interested in [FLO](https://wiki.snowdrift.coop/about/free-libre-open) funding models (I'm on the [snowdrift.coop](https://wiki.snowdrift.coop/about/intro) volunteer team).

**Comment by tibbi** [comment]
Hey, Im not paid for them. Its just my side project on which I spend all my free time. My fulltime job is the Android app of https://www.gruveo.com/ . I recently added some donating options to simplemobiletools at http://simplemobiletools.github.io/donate/ , I see a huge potential there, it just needs time ;)
