### ISSUE TITLE
How to set default phone number in Simple Contacts Pro

### ISSUE THREAD

**Issue by alcoolfire** [SimpleMobileTools/General-Discussion#113]
I have been unable to find a way in Simple Contacts Pro to set which of several phone numbers in any particular contact entry should be the default when placing a call. How do I accomplish this?

Also, what is the default behaviour for all entries? First phone number, first mobile phone number, randomly chosen?

**Comment by tibbi** [comment]
setting a default number is not supported yet. Duplicate of https://github.com/SimpleMobileTools/Simple-Contacts/issues/159
