### ISSUE TITLE
[Feature anti-request] Do not support sync initiation in Simple Contacts (Pro)

### ISSUE THREAD

**Issue by alcoolfire** [SimpleMobileTools/General-Discussion#114]
I am a firm believer that when someone gives me their personal contact information that it would be grossly unethical for me to share that information with a third party without first getting permission from that someone. As a result, my first step in configuring any Android phone is to disable auto-sync for contacts. Only after doing that will I load the phone with any contact information. Following that I will NEVER knowingly initiate a manual sync either. This worked for many years, with Google never getting a copy of my contacts list. That all changed when the Google Contacts app was updated to add the "feature" where downward swiping the contacts list initiates a manual sync even when auto-sync is still disabled. As it is in practice impossible to avoid occasionally downswiping, Google has now stolen my contacts list. To put it mildly, I am very angry with Google. Upon discovering that Google Contacts is now effectively malware, I removed that app from my phone, discovered Simple Contacts (Pro), and am very happy to find that it seems to have NO mechanism for initiating a manual sync. Thank you for that!

So here is my anti-request. Please, please, please be sure to NEVER add functionality for triggering a sync to the cloud from this great app of yours. And, if for any reason you feel you must, please make it a feature that is completely disabled by default requiring an opt-in with some kind of very explicit setting for those users that don't concern themselves with the ethics of sharing other people's personal information.

**Comment by tibbi** [comment]
contacts are stored on the device itself, I cannot even sync any cloud syncing function at all. It doesn work like that. Thanks

**Comment by alcoolfire** [comment]
I'm not speaking about the app itself doing the syncing, but rather triggering the OS to do the sync. The Google Contacts app does that when you downswipe and it too relies on the system contacts database.
