### ISSUE TITLE
Androlyzer Report and ideas

### ISSUE THREAD

**Issue by Alexanderlll** [SimpleMobileTools/General-Discussion#116]
Hello, i Androlyze all SimpleMobileTools apps and this is what i found

![Screenshot_20190731-154225](https://user-images.githubusercontent.com/53236433/62416051-402dcd00-b5f1-11e9-915c-1e83a0007ba3.png)

i want to be realist about Androlyzer, is not updated since 2016 and after scan a lot of apps, i think Androlyzer has no capability for differentiate a clean link and a real leak, for Androlyzer everything goes to internet from an internal link is a leak so, but, it really shows an interesting way for see how an app works

Almost all SimpleMobileTools shows user input to network leak, but i think this happens because About tab links redirects to a browser or an related app like Play Store, Facebook or Reddit, and local images to network leak happens when you touch the logos in About tab, it is correct? i dont know about the other leaks but, in SimpleContacts shows Contacts to network leak, in SimpleCalendar shows Calendar to network leak and in SimpleGallery shows Photos to network leak, sockets to network leak in all apps too, SimpleFlashlight appears as clean with no leaks, clock and calculator appears clean too.

SimpleMobileTools are a clean apps suite, trustworthy, i use them and recommend, but i think there is another way to handle the About tab links, like an Open With dialog instead of redirects to a browser or an app without confirmation or even a posibility for choose a favorite browser, Thanks for your time.

**Comment by tibbi** [comment]
Hey, those are casual links, nothing wrong with that :) The apps dont even have access to the internet, so there definitely cannot be anything wrong with them. So thanks, but I dont want to change any link behaviour.

**Comment by Alexanderlll** [comment]
yeah it is nothing wrong about, i use your apps, i agree with your position, im not attacking
