### ISSUE TITLE
Unescaped apostrophe in string

### ISSUE THREAD

**Issue by Alessandroinfo** [SimpleMobileTools/General-Discussion#117]
I receive this error with version: `implementation 'com.simplemobiletools:commons:5.16.13'`

Error: `\.gradle\caches\transforms-2\files-2.1\2f270e3ac4381d034b0ffdafa510884a\jetified-commons-5.16.13\res\values-cy\values-cy.xml:497:5-505:14: AAPT: error: unescaped apostrophe in string`
    
I found an apostrophe without escape here:

   ```
 <string name="new_app">
        <![CDATA[
            S\'mae,<br><br>
            Jyst yn rhoi gwybod i ti am ap newydd wedi\'i ryddhau yn ddiweddar:<br><br>
            <a href="%1$s">%2$s</a><br><br>
            Gellir ei lawrlwytho gan glicio'r teitl.<br><br>
            Hwyl.
        ]]>
    </string>
```

**Comment by tibbi** [comment]
that is the old Commons, it is causing errors just because of the updated gradle, kotlin, or so. Just use the latest one.
