### ISSUE TITLE
Linked Indonesian translation

### ISSUE THREAD

**Issue by zmni** [SimpleMobileTools/General-Discussion#118]
Currently there are 2 language code for Indonesian `-id` and `-in` and we have to maintain both each time we make change. This is repetition we wish to avoid.

Can you just link `-in` to `-id` like [F-Droid do with their android client](https://gitlab.com/fdroid/fdroidclient/blob/master/app/src/main/res/values-in)? It's a file with a reference to the other language code. I don't know if this will work here, but it work with F-Droid.

Would you try and test it with one app first? If it work I can do it for the rest.

Thank you.

**Comment by tibbi** [comment]
It isnt possible. the app takes the strings from some file directly, I cannot cross reference them in any way. Thanks
