### ISSUE TITLE
Add a video player

### ISSUE THREAD

**Issue by beerisgood** [SimpleMobileTools/General-Discussion#12]
Please add a video player which use up-to-date stuff.
VLC isnt good, its outdated (just check F-Droid)

**Comment by tibbi** [comment]
maybe in the further future, dont expect it anytime soon

**Comment by beerisgood** [comment]
Fair enough

**Comment by mueller-ma** [comment]
@beerisgood Do you miss features in the vlc on fdroid?

**Comment by beerisgood** [comment]
Not realy.
It only looks VLC is not active maintained and using a video player without updates/ with security bugs is a bad idea.

**Comment by mueller-ma** [comment]
You could download it from the website or create your own fdroid repo and include the apk from videolan.org

**Comment by Jazcafe** [comment]
What's wrong with the video player in Gallery?

**Comment by beerisgood** [comment]
The default galery is a system app and i like user apps

**Comment by Jazcafe** [comment]
Sorry, I was thinking of the Simple Gallery not the default app..
