### ISSUE TITLE
please make a simple simple dead simple video mobile to mobile nanny cam. I will tip

### ISSUE THREAD

**Issue by cellurl3** [SimpleMobileTools/General-Discussion#121]
I need a nanny cam. No frills. I am a dev, so I will customize for my needs. (RC car to be exact).

Thanks for consideration.
I like your consolidation system.

Jim 
Memphis

**Comment by tibbi** [comment]
Sorry, but it doesnt fit the apps suite at all. And it cannot be made offline.
