### ISSUE TITLE
Shared Theme makes some apps unusable

### ISSUE THREAD

**Issue by ThePreviousOne** [SimpleMobileTools/General-Discussion#122]
I was using Black & White theme in all suite apps, but recently I the share theme button (forget what it says), anyway once I set that I could no longer open some other Simple apps without them crashing immediately.

Im running the latest F-Droid builds
tested against the debug builds some work some don't (I'm not testing every app)

~~the issue seems to have been fixed for Music Player but still exists in File Manager, and Gallery doesn't have the problem but Draw does(didnt test debug version)~~

**Comment by tibbi** [comment]
if you reinstall the broken apps, does it work well?

**Comment by ThePreviousOne** [comment]
I tried clearing data and cache earlier which did nothing. Just reinstated now that fixed everything.
Thanks
Wonder what happened? I even tried logcat but saw nothing relevant

**Comment by ThePreviousOne** [comment]
I'll try to reproduce it tomorrow and post anything I find here

**Comment by tibbi** [comment]
not sure, could be some glitch related to the navigation bar color maybe. Make sure you really use the latest version of every app.

**Comment by ThePreviousOne** [comment]
So I tried to reproduce it on my phone by uninstalling simple app suite then reinstalling, to my surprise my previous settings where still there. but I wasnt fully able to reproduce the bug, I did get some weird results though. However on a VM I couldnt do It at all.

I'll keep digging when I have time but I'm in the middle of a few other projects right now

**Comment by tibbi** [comment]
guess its ok already, nobody else reported anything like that. It will be possible to disable Shared Theme by disabling it in Simple Thank You, it wont be needed to uninstall it anymore.
