### ISSUE TITLE
Simple Mobile tools

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/General-Discussion#125]
Hi, which is your new/upcoming app??

**Comment by tibbi** [comment]
I dont know, just released Simple Dialer at https://play.google.com/store/apps/details?id=com.simplemobiletools.dialer

**Comment by Pranab009** [comment]
I install this some day's ago...😁♥️

**Comment by Pranab009** [comment]
I'm install it few day ago..😁♥️

**Comment by Pranab009** [comment]
But built it like your gallery app (compact)..🙏🏻❤️

**Comment by Pranab009** [comment]
Please devolop a internet speed indicator.
My device is stock android so no native speed indicator inside it & i can't
like other apps..
I'm almost use your all apps..
They are tooo good...
