### ISSUE TITLE
Please develop a internet speed meter

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/General-Discussion#126]
Hello, I'm using stock android and i can't see any open source internet speed meter/indicator.
Please please try to work on it...🥺🙏🏻🙏🏻

Thank you for reading this...

**Comment by tibbi** [comment]
our apps are offline, so an internet speed meter obviously wont be created

**Comment by Rikk** [comment]
Speed meters don't need to make connections by themselves, they just watch the connections, ie. they need only "view network connections" and "view wi-fi connections" permissions. I suppose, therefore, they can be considered offline apps, even though they understand about connections, right? In the end, they might be just calculators of sent/received Internet traffic, as reported by Android system.

**Comment by tibbi** [comment]
not really, a speedmeter definitely cannot work without internet access :)

**Comment by Rikk** [comment]
I disagree. Not sure we are talking about the same thing, but I'm talking about an informational app that is used to display the current transfer rate ((k/m/g)bytes/sec) of the active Internet connection. If there's no traffic it could show a zero. This kind of apps usually also has interface showing cumulative daily/monthly amounts of data the user transfered.
I think above is the kind of apps mentioned in op. Not to confuse with an app that tests the speed of downloads/uploads ("speed meter"?).

**Comment by tibbi** [comment]
nothing related to the internet can be accessed without permissions
