### ISSUE TITLE
New app suggestions

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/General-Discussion#128]
Hello, 
Devoloper sir, 

Your all apps are tooo good.👍🏼
I'm using your your all apps..
I'm really fan of you..
We need some more apps from your Simple Mobile Tools Lab please try to make this type of apps..
Please.. please... please

Clip board manager

Screenshot manager

Browser

Keypad 

Blue light filter

App lock

Dictionary

**Comment by vanillajonathan** [comment]
- Maps
- Remote (IR/Bluetooth)
- Tasks / todo
- Text editor
  - Code editor
 - Terminal
 - Translator
 - Touchpad (for drawing on desktop computer)

**Comment by tibbi** [comment]
keyboard has just been added recently, dont really expect any new ones anytime soon. And report them one by one anyway.
