### ISSUE TITLE
simple dialer - contact info instead of "standard app" dialog

### ISSUE THREAD

**Issue by ihaake** [SimpleMobileTools/General-Discussion#129]
Made the "simple dialer" the standard app for dialing.
In it's call history I'd like to get contact details. E.g. by pressing longer on an entry, ...
All I get is a dialog asking to set "contacts" the standard app for dialing.

"contacts" could be my choice for the standard app for dialing, if it had a call history.
But mixing the topics "call history" and "contacts" isn't the right solution, I agree.

**Comment by tibbi** [comment]
just upgrade to the latest Simple Contacts 6.11+, it had its calling capabilities removed. I wanted to add Call History into Simple Contacts, but Google didnt grant me the permission to access the call log even after requesting and appealing multiple times.

**Comment by ihaake** [comment]
> Simple Contacts 6.11+
... is not available via fdroid yet.
Is there another place to download the apk?

**Comment by tibbi** [comment]
if you dont want to wait a few days all .apks are available on Github too, at https://github.com/SimpleMobileTools/Simple-Contacts/releases .

**Comment by ihaake** [comment]
THX!
getting used to github slowly :-)

**Comment by ihaake** [comment]
So, what remains is kind of convenience.
In the beginning I suggested: 
In the call history of the dialer I'd like to get contact details of a certain history entry directly and easily - e.g. by pressing longer on that call history entry. 
The effect: the contact details are presented directly and I don't have to look it up seperately in the contacts tab. 
Saving several clicks.
Surely no bug but convenience. But maybe worth a thought.

**Comment by tibbi** [comment]
well many UI improvements are on the roadmap, sadly some code had to be duplicated between Dialer and Contacts. It will be improving over time to work as expected.
