### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by linuxcaffe** [SimpleMobileTools/General-Discussion#13]
First off, I really like this software suite, just my speed and Open Source is the way to go.

Sometimes, when you have a quick question or a dumb idea, Internet Relay Chat is a great development tool. I frequent irc.freenode.net, and it's easy and free to start a #simplemobiletools channel.

If the developers already enjoy  an existing server/ channel, please publish the coordinates.

thanks fer the awesome software!

**Comment by tibbi** [comment]
Hey, theres no channel, as Im the only developer :) I dont really want to start a chatting channel, just use github or emails. Reports on github usually get responses from different people too.

**Comment by linuxcaffe** [comment]
ok, cool, github it is!
