### ISSUE TITLE
[Feature Request] "Follow System Theme"

### ISSUE THREAD

**Issue by Prog1563** [SimpleMobileTools/General-Discussion#135]
I have been using your apps for a while now on LineageOS and absolutely love the work that y'all have done!
There is one thing that has been bugging me a little lately though with the advent of LOS 17.1... The new theme engine...
It would be absolutely spectacular if we had an option to "Follow system theme" instead of setting the colors ourselves.

Maybe there is a way to use the system's background, text and accent colors?

I'm not sure what the compatibility looks like for other AOSP/Android distributions or if this is even possible, but either way I would love to hear back 👍 

Keep up the great work everyone! ❤️

**Comment by tibbi** [comment]
you mean toggling dark/light themes, or something more advanced?

**Comment by CyberneticCody** [comment]
I mean something more advanced. And again, I am not sure if this is possible...
What I mean is actually using the accent color and the light/dark mode of the device that you set in Android's settings (Settings > Display > Advanced > Styles & Wallpapers > Edit > Color)

Looking a bit deeper though, this may be specific to Lineage OS, but I believe it also applies to Oxygen OS (OnePlus Phones).
I don't know how compatible the API is though or if it is different between ROMs
https://wiki.lineageos.org/sdk/api/styles.html

**Comment by tibbi** [comment]
dont you mean this? https://github.com/SimpleMobileTools/General-Discussion/issues/58

**Comment by CyberneticCody** [comment]
Yes and no... I would try to avoid using APIs that are specific to just one ROM, but seeing that they moved to the Android 10 built in theme picker maybe this is more possible than I thought :)

**Comment by proletarius101** [comment]
What he mean is https://material.io/develop/android/theming/dark, which is a built-in feature of material design (and we are already using the material library). Are you interested in switch the base theme from `Theme.AppCompat` to `Theme.MaterialComponents.DayNight` (with automatic action bar) or `Theme.MaterialComponents.DayNight.NoActionBar`? If you don't have time to do this or have no idea how it works, I will be happy to make a PR

**Comment by tibbi** [comment]
I will have to play around with it, not sure how it works or looks now

**Comment by proletarius101** [comment]
> I will have to play around with it, not sure how it works or looks now

If you need any help or don't know how to do it correctly, I can do with the simple transition as I've done it for F-droid and FairEmail.

**Comment by theotheroracle** [comment]
ok so this issue doesn't sem to be specifically about the dark / night mode setting, as mentioned here https://github.com/SimpleMobileTools/General-Discussion/issues/135#issuecomment-692238806 although honestly, just having two themes to switch between, or just switching the background colour, etc., is all i'm really looking for . it would be nice if it got colours from the system UI, but i think the dark / night theme is more important . should i make a seperate issue for that specifically ? or does that just fall under the scope of this one ?

**Comment by Prog1563** [comment]
The following screenshots from my OP8T is what I am talking about with the "Follow system theme" since you can change from light/dark (day/night) mode and change the system accent colors.

![Screenshot_20210608-102635](https://user-images.githubusercontent.com/55600371/121203712-51c30a00-c844-11eb-9204-376787d405ea.jpg)
![Screenshot_20210608-102646](https://user-images.githubusercontent.com/55600371/121203717-52f43700-c844-11eb-92a6-9894b4840a53.jpg)
![Screenshot_20210608-102628](https://user-images.githubusercontent.com/55600371/121203791-630c1680-c844-11eb-85bb-3e832a40ff78.jpg)

**Comment by theotheroracle** [comment]
yeah i know

**Comment by theotheroracle** [comment]
those are still two seperate things though

**Comment by Prog1563** [comment]
Oh wait, I got you. Sorry, misread your post, my bad...

In regard to both though, I think Android 12 might put a lot of this up in the air. Looks like they are doing a massive UI overhaul that might change a LOT of these conversations.

**Comment by tibbi** [comment]
a new Auto theme has just been added into Simple Commons, it will eventually reach all apps starting with App Launcher and Calculator. It will toggle text, background and navigation bar colors, we cannot really access or use the system accent color

**Comment by zhaofengli** [comment]
On Android 12, [Material You](https://material.io/blog/announcing-material-you) is available and the system palette is accessible through [the `@android:color/system_*` resources](https://developer.android.com/reference/android/R.color#system_accent1_500). On the platform side, the wallpaper color extractor is closed-source and not available in AOSP yet, though it's [expected to be added](https://www.xda-developers.com/android-12-1-monet-open-source) in the upcoming version and [an alternative implementation](https://github.com/kdrag0n/android12-extensions) is available. You can use the 12.1/Sv2 emulator images to test.

**Comment by julianfairfax** [comment]
> a new Auto theme has just been added into Simple Commons, it will eventually reach all apps starting with App Launcher and Calculator. It will toggle text, background and navigation bar colors, we cannot really access or use the system accent color.

How come unlike the other theme options, this can't be applied to all apps in one click?

**Comment by julianfairfax** [comment]
Apps using the auto theme option also don't switch themes immediately after the theme has been switched, but only after closing and reopening the app..

**Comment by tibbi** [comment]
1. because you can set either Auto or Shared theme, not both
2. theme should be switched right after confirming it. If not, it might be some issue with specific colors or some system specific glitch

**Comment by julianfairfax** [comment]
> 1. because you can set either Auto or Shared theme, not both

Why is that?
> 2. theme should be switched right after confirming it. If not, it might be some issue with specific colors or some system specific glitch

No, that works fine. What I mean is if I set the theme to auto and then change the system theme, it doesn't change the app's theme to the new system theme until I close and reopen it
