### ISSUE TITLE
[Request] Simple Dialer+Simple Contacts

### ISSUE THREAD

**Issue by RickyM7** [SimpleMobileTools/General-Discussion#136]
It would be amazing if Simple Dialer and Simple Contacts apps were merged into a single app. They complement each other and the joining of the two would make life easier for those who use the two apps.

**Comment by tibbi** [comment]
they used to be, but the app hasnt received the permission to access the call logs by Google. A standalone Simple Dialer had to be published, thats core functionality is calling.

**Comment by RickyM7** [comment]
Any chance that a merged version of the two apps will be released exclusively on F-Droid? Or would it be a waste of work, since you always post the apps in the Play Store too?

**Comment by tibbi** [comment]
I definitely dont want to do duplicate work, so no.

**Comment by RickyM7** [comment]
I completely understand. Thank you so much for the answers.
