### ISSUE TITLE
Apps Revert to Shared Theme

### ISSUE THREAD

**Issue by CivBase** [SimpleMobileTools/General-Discussion#139]
I configured a "Shared" theme for my apps, then decided that I wanted each one to have its own theme.  Now I cannot set the theme to anything except for "Shared".  If I change the theme in any SimpleMobileTools app to something else (eg "Custom" or "Dark"), it automatically reverts back to "Shared" within a couple minutes.  I can still modify colors in the "Shared" theme, though, and it updates the other apps accordingly.

In case it matters, I have an LG V30 with Android 9 using the "Home" launcher that came with the phone.  I installed the following SimpleMobileTools apps with F-Droid and the issue persists on all of them:

- Calculator (v5.4.0)
- Calendar (v6.11.2 Pro)
- Clock (v5.4.0)
- Gallery (v6.17.3 Pro)
- Notes (v6.5.6 Pro)
- SMS Messenger (v5.5.1)
- Thank You (v5.2.0) <- via Google Play Store

**Comment by tibbi** [comment]
Just disable Thank You. Some way of overring it is on the roadmap.

**Comment by CivBase** [comment]
That worked.  Thanks!

**Comment by tibbi** [comment]
starting with Simple Thank You 5.3.0 if you disable Shared Theme in Simple Thank You, it wont be forced to any app. You wont have to uninstall it anymore.
