### ISSUE TITLE
Add icons for tar, gz, xz, bzip2 file extensions

### ISSUE THREAD

**Issue by bac1** [SimpleMobileTools/General-Discussion#141]

**Comment by tibbi** [comment]
to what app? This doesnt really belong to the general discussion

**Comment by bac1** [comment]
@tibbi in file manager. just files with descriptions of svg paths are stored in https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/res/drawable/ic_file_{extension name}.xml. So I thought the issue should be created here. Sorry
