### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by bac1** [SimpleMobileTools/General-Discussion#142]
1. All long descriptions always contains duplicated lines:

        It comes with material design and dark theme by default, provides great user experience for easy usage. The lack of internet access gives you more privacy, security and stability than other apps.

        Contains no ads or unnecessary permissions. It is fully opensource, provides customizable colors.

        <b>Check out the full suite of Simple Tools here:</b>
        https://www.simplemobiletools.com

        <b>Facebook:</b>
        https://www.facebook.com/simplemobiletools

        <b>Reddit:</b>
        https://www.reddit.com/r/SimpleMobileTools

Maybe it could be moved to simple / common in an element called for example long_description_footer?
Or  at least:

        <b>Check out the full suite of Simple Tools here:</b>
        https://www.simplemobiletools.com

        <b>Facebook:</b>
        https://www.facebook.com/simplemobiletools

        <b>Reddit:</b>
        https://www.reddit.com/r/SimpleMobileTools

2. What tool did you use to create the file extension icons for simple / file-manager?

**Comment by tibbi** [comment]
1. I like it like that, it is easier to maintain
2. I bought them, dont remember where now

**Comment by bac1** [comment]
@tibbi in this case, a uniform style of footer translation would be observed for all apps

**Comment by bac1** [comment]
@tibbi if these lines were in simple/common, then they could only be translated once. And it wouldn't happen that some bac1 translate the same strings differently.

**Comment by tibbi** [comment]
it is a lot easier to main like this for me
