### ISSUE TITLE
Make "Accent color of white theme" avaible for other themes

### ISSUE THREAD

**Issue by jnnkB** [SimpleMobileTools/General-Discussion#144]
When using for instance the black and white theme you don't have this possibility. Therefore its hard to tell whether a switch is in an on/off state. I think an black theme which looks like the black and white one but has an accent color would be cool.

PS: I think the new white theme looks really good.

**Comment by tibbi** [comment]
ye adding it to B&W is on the roadmap, I added the string for it already. For now it wont be available to other themes, seems useless there

**Comment by tibbi** [comment]
I just added it actually, will be in the Music Player first. Every app will eventually receive it once updated.
