### ISSUE TITLE
Request feature to select ringtone for dialer as in simple clock 

### ISSUE THREAD

**Issue by priv4cy** [SimpleMobileTools/General-Discussion#147]
Ringtone options on my Samsung m21 can be set as alarm ringtones in simple clock app.

It would be great if this feature is made for dialer. I'm talking about the ringtone that will ring on incoming calls. 

Best regards.

**Comment by tibbi** [comment]
What OS version do you have? Ringtone picking is done differently in some apps in some cases

**Comment by priv4cy** [comment]
Android 11

**Comment by tibbi** [comment]
Ringtones should be handled by the system, not us. I dont think think it is our responsibility to replace the disabled system services.
