### ISSUE TITLE
You're luring users

### ISSUE THREAD

**Issue by monblaz0** [SimpleMobileTools/General-Discussion#148]
simplemobiletools.com is not giving users all the info they need about the different versions of your apps and I believe this is made on purpose.

For instance on the page dedicated to the Notes app there is no info that the "Pro" version is available for free on F-droid, there's only a Get it on Google Play button, no F-droid button whatsoever. You talk about free and pro versions, which only leads to confusion since the "Pro" version is available for free on F-droid.

F-droid users are bluntly ignored. This site is clearly aimed at the Google play audience, showing them why they should get the paid version of the apps, never showing them the way to step out and get the same app for free on a much more privacy and freedom friendly repository. Doing so you're luring them.

**Comment by Secret-chest** [comment]
> simplemobiletools.com is not giving users all the info they need about the different versions of your apps and I believe this is made on purpose.
> 
> For instance on the page dedicated to the Notes app there is no info that the "Pro" version is available for free on F-droid, there's only a Get it on Google Play button, no F-droid button whatsoever. You talk about free and pro versions, which only leads to confusion since the "Pro" version is available for free on F-droid.
> 
> F-droid users are bluntly ignored. This site is clearly aimed at the Google play audience, showing them why they should get the paid version of the apps, never showing them the way to step out and get the same app for free on a much more privacy and freedom friendly repository. Doing so you're luring them.

Especially with all the reviews on simple gallery now.
