### ISSUE TITLE
Apps pinging Matomo

### ISSUE THREAD

**Issue by vsanjay85** [SimpleMobileTools/General-Discussion#149]
Installed a couple Simple apps - Dialer, Clock, Voice Recorder - and noticed these calls to Matomo on pi-hole.

Tried searching for "matomo" and "piwik" (matomo previous name apparently) and found nothing at first glance. 

What data are you sending to Matomo and where is it in the code? 

<img width="815" alt="image" src="https://user-images.githubusercontent.com/18194044/121526514-709dd980-c9c7-11eb-9f59-5398002ed77c.png">

Also saw this, but not 100% sure if it's me going to your website or if it's the app(s) doing it:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/18194044/121526489-6976cb80-c9c7-11eb-8214-a3690b40fd4b.png">

**Comment by tibbi** [comment]
well just search for "matomo" at the source code, it is quite self explanatory. It contains some basic analytics only.

**Comment by vsanjay85** [comment]
As I said in the original comment, I did that and found nothing. Can you maybe take a second and paste the URL to the code or the search result here?

**Comment by tibbi** [comment]
view-source:https://www.simplemobiletools.com/

**Comment by vsanjay85** [comment]
Thanks!

So just to confirm, Matomo's only on the website and none of the apps you create use Matomo. Is that what you're implying?

**Comment by tibbi** [comment]
sure, the apps have no internet access
