### ISSUE TITLE
Add shadow to icons

### ISSUE THREAD

**Issue by mueller-ma** [SimpleMobileTools/General-Discussion#15]
I found a [website](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=description&foreground.space.trim=0&foreground.space.pad=0.2&foreColor=rgb(255%2C%20255%2C%20255)&backColor=rgb(245%2C%20146%2C%200)&crop=0&backgroundShape=square&effects=shadow&name=ic_launcher) which creates a material icon with shadow in a few clicks. I created two icons for the notes app. What do you think about them (sure, thats the wrong orange)?
![web_hi_res_512](https://cloud.githubusercontent.com/assets/22525368/24320042/db1ac140-112c-11e7-8110-9e15ea3c43b9.png)
![web_hi_res_512](https://cloud.githubusercontent.com/assets/22525368/24320045/df51443c-112c-11e7-950a-c75bebb3935f.png)
Here is a link to the icon with the right color: [link](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=description&foreground.space.trim=0&foreground.space.pad=0.2&foreColor=rgb(255%2C%20255%2C%20255)&backColor=rgb(246%2C%20134%2C%2048)&crop=0&backgroundShape=square&effects=shadow&name=ic_launcher)

**Comment by tibbi** [comment]
I dont like material icons, they just dont look natural at all. Its just G+ using it, no other serious apps.
