### ISSUE TITLE
Remove recurring "Rate our app please :)" popups

### ISSUE THREAD

**Issue by diodelass** [SimpleMobileTools/General-Discussion#150]
F-Droid builds of these apps produce "Rate our app please :)" popups directly after launch at regular intervals, asking me to pick from five star levels. I have had these apps installed for multiple years now, and the interruptions just keep coming, no matter how many times I dismiss them. 

Apart from being rude and disruptive even at the best of times, this mainly just seems pointless for everyone when the app in question was installed from F-Droid. F-Droid has no star rating system for apps, and even if my phone had Google Play services installed (which it does not), I would still not be able to leave a rating there because Google Play would still have no record of me installing the app in the first place. 

I think that these popups should be removed entirely from all builds, because they interrupt the user at a moment during which they are virtually guaranteed to be busy. If you insist on keeping them anyway, then I really think you should consider at least removing them from F-Droid builds and limiting the number of times that they can recur. One interruption was forgivable, but infinite interruptions is not - and continuing to harass your users indefinitely is not a good way to get them to leave favorable reviews.

**Comment by tibbi** [comment]
Just press a star and it won't appear again.
