### ISSUE TITLE
[Feature Request] Adding Show/Hide buttons for calendars

### ISSUE THREAD

**Issue by Thulkash** [SimpleMobileTools/General-Discussion#151]
Hi,

Simple Calendar would be awesome (it is already the case but would be much greater) if you could implement a show/hide button for different calendars we configure in your app Simple Calendar, like Business Calendar.
It would be very much better if we could hide/show calendars instead of erase/resync them, with an option to choose which calendars we want to show/hide quickly.

You can see the buttons from Business Calendar with this link: https://play-lh.googleusercontent.com/Rin6zpoUrQZgxPNEEveCCe7T3_KridH1ksNmD7vAWogCUrztVq1SLXUe0qCohxaytp4=w2560-h1311-rw

Thanks a lot for your apps!

**Comment by tibbi** [comment]
you can use Filter at the top menu, it is quick too
