### ISSUE TITLE
Bug With Thank You App Causing Shared Theme To Be Same As Custom Theme

### ISSUE THREAD

**Issue by gitlabber27** [SimpleMobileTools/General-Discussion#152]
Bug with Thank You app. Once the Thank You app is installed and shared theme is enabled on all installed Simple Mobile Tool apps the custom theme no longer works. Shared theme and custom theme always stays identical. I have to uninstall the Thank You app in order to set a custom theme.

**Comment by tibbi** [comment]
just select a different theme in Simple Thank You and it will stop the sharing

**Comment by gitlabber27** [comment]
Thanks I should of caught that. Forgive my stupidity.
