### ISSUE TITLE
Translated app titles and descriptions in Google Play are different than in values.xml

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/General-Discussion#155]
Hi,

I've noticed that in Google Play titles and descriptions of Simple Apps are different from those that are in values.xml files. For example, I've translated these texts for Simple Dialer, but in Google Play I can see the text that looks like it's straight from the automatic translator.

Would it be possible to use the texts we've translated in values.xml?

Thanks!

**Comment by tibbi** [comment]
I'm always A/B testing something, so they can differ. All translations have been done by people though, not any automatic translator. Do you mean the polish language?

**Comment by Aga-C** [comment]
Yes, I mean the Polish language.

**Comment by tibbi** [comment]
right, I will keep the current descriptions for now as they performed better, will retest them in the future. Thanks
