### ISSUE TITLE
Some apps in F-Droid don't have translated titles and/or descriptions into Polish

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/General-Discussion#156]
Hi,

In F-Droid (app and website), some apps don't have titles and/or descriptions translated into Polish, when others have (similarly as in Google Play). Apps without translations are:
- Simple Calendar Pro
- Simple Dialer
- Simple SMS Messenger
- Simple Gallery Pro (just title)

They all have Polish titles and descriptions in values.xml. For all of them (despite Simple Gallery Pro), I did translations from the scratch some time ago, they didn't have Polish version earlier. In case of Simple Gallery Pro, the description is not updated to the latest version.

Sample screenshots:
![image](https://user-images.githubusercontent.com/85929121/128624123-4ca1cd57-80ff-49d7-8937-b12677d8e142.png) 
![image](https://user-images.githubusercontent.com/85929121/128624137-b414fff7-6c12-41f5-8f17-bb7ad538b928.png)

Could you update the descriptions with the next updates?

Thanks!

**Comment by tibbi** [comment]
we use the fastlane system for that, try creating pull requests please and creating the files. Here is an example of Simple Calendars german translation https://github.com/SimpleMobileTools/Simple-Calendar/tree/master/fastlane/metadata/android/de . Thanks

**Comment by Aga-C** [comment]
Ok, I will check it out. Thanks.
