### ISSUE TITLE
if primary color and background color are set to white, some text can't be seen

### ISSUE THREAD

**Issue by sigasigasiga** [SimpleMobileTools/General-Discussion#157]
if i want to have completely white application (for example like on instagram -- white header and white body) i need to set both background and primary colors to white. but if i do so, buttons become invisible because text color blends with a background ![like so](https://user-images.githubusercontent.com/48245894/129459943-c71bca16-29d1-4b75-a7d9-d3ee10942415.png)

i've checked it in gallery and file manager but i think this problem is common across all simple apps

**Comment by tibbi** [comment]
if you pick same colors, of course they wont be readable. Not much to do with it.
