### ISSUE TITLE
[Improvement] Collapse/expand FAQ questions

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/General-Discussion#158]
Hi,

I thought that it could be useful to provide an option to collapse and expand questions in the FAQ section of all apps. It would make the FAQ easier to navigate and the user would see more questions on one screen.
From what I've found, it's possible to do this with a List component in Material Design which supports expand and collapse similar to accordion components on the Web.

What do you think about it?

**Comment by tibbi** [comment]
I dont like collapsing such things, makes it difficult to read through
