### ISSUE TITLE
Simple, Stable, Easy mobile Tools

### ISSUE THREAD

**Issue by PinkPlasticBeach** [SimpleMobileTools/General-Discussion#160]
Dear Tibor,

I'm a real fan of your apps. I found them on F-Droid a few months ago and soon after decided to become a patron. I saw you we're constantly active and putting a lot of love in those apps. I believe in FOSS and wanted to say thank you with a small (3€) but constant pay for important apps that would work straight-forward, do the basic stuff reliably and without adds.

In my Opinion you were fast to close two of my feature-Request. ([1470](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1470),[1469](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1469))
You're apps are named "simple", you cant meet all wishes and It's okay to say no.

But as I see there's more and more "simple apps" I want to ask you something in general:

If the workload is getting too much, please consider dropping some of the apps to make sure the other apps really work well. First of all without major bugs and also convenient and straight-forward in all basic functions.

I want to recommend those apps to friends (on Play-Store, too) without having to explain anything. I want to say "It's not fancy but it does the basic job very well". I believe this is the intention of the simple tools.

Gallery and Calendar are most important for me, like for many others. If I knew coding I would gladly help. Please consider concentrating on few apps and make them really good in their core functions.

This is not the case right now:

- Creating other [events](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1470) as reminders for another event might work, but its just not elegant. As "notifications" are a key part of smart-calendars they should simply work out of random limits like one/two/three hour/day/week.
- A [Bug](https://github.com/SimpleMobileTools/Simple-Gallery/issues/2199) i filed for the gallery concernes rotating images on SD-Card. Its common to store images on SD, it's very common to rotate. I know the Storage Access Framework of Android is a big problem, but I'm eagerly waiting for this to work at some time in the future.
- Editing repeated Calendar-Events leaves a false Ghost-Event in the online-Calendar. This is a crucial [Bug](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1358) that creates real-life problems

It's three examples of things that do frustrate in everyday use. There's other important Issues reported by other people. My Intention is not to complain here. I'm really hoping to go a long way with your apps and it's okay if bugs/ideas take time to fix/develop. But please don't close issues, just because there's too much work.

Thanks for the Work! Kind regards

PlasticBeach

**Comment by tibbi** [comment]
Well, if something is on the roadmap, I keep is open. But some of your requests were really unusual ones and while the gallery and calendar have millions of active daily users, nobody else requested it. If I added every feature 1 person requested the apps would be flooded with useles features already.

**Comment by PinkPlasticBeach** [comment]
Hey again,
You need to make choices, of course,  I do understand.

I've been writing a lot on those ideas and it might look complicated. I'll reply there again. ([1470](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1470),[1469](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1469))
Its really just what my dumb 30$-nokia 100 could do already: choose the _time_ of an alarm and make it _loud or silent._

But there are severe issues:
- [ Critical bug: file lost after a move action #1650 ](https://github.com/SimpleMobileTools/Simple-Gallery/issues/1650#issue-528323744)
That Bug is open since 2019
- the calender-bug is open since April and it caused a day with no one at shift in my Team. 
- rotating images is a key function of gallery as well.

If you tell me it needs time for fixing and developing, we're on the same page.

If you tell me I ask too much, and others dont need this:
Most of the People I know don't even know what a bug report is or how to file one. Look at Windows 10 - Look at outdated, buggy Androids: Billions of Users.
People take what they get and use as much as works.

I'm sure more than me would use the features if they were present. I'm sure more than me were happy without those bugs.

I think it's some bits that would make those good, simple apps perfectly easy.

I know it's work. You're a single developer and most FOSS-Projects take lots of time to become truly finished. But others die in too much bugs and too much work.

I don't want simple tools to die. I want to support you. I'll be patient with the fixes and ideas.

But please don't tell me it's useless.

Kind Regards

**Comment by tibbi** [comment]
sure, many improvements are on the roadmap, stay tuned
