### ISSUE TITLE
Add: "one", "few", "many" and "other"

### ISSUE THREAD

**Issue by Valdnet** [SimpleMobileTools/General-Discussion#161]
In text strings there is no plural for the values 2, 3 and 4. In various languages, e.g. in Polish, the inflection for the plural differs from the number 5, 6, etc.

Example:

> 1 album
> 2 album**y**
> 3 album**y**
> 4 album**y**
> 5 albumów

For text strings with plural, add:

```
<item quantity="one"></item>
<item quantity="few"></item>
<item quantity="many"></item>
<item quantity="other"></item>
```
so that translators see that these variations need to be translated.

**Comment by tibbi** [comment]
well, that should be handled by the translators at translating

**Comment by Valdnet** [comment]
Not all translators know coding. They translate directly text strings that appear in the file.

**Comment by tibbi** [comment]
Most of them are aware of it. I cannot add all required variants into over 35 languages.
