### ISSUE TITLE
Dialer and Contacts contacts list isn't synced

### ISSUE THREAD

**Issue by SNvMK** [SimpleMobileTools/General-Discussion#162]
Hi, sorry if it was already asked and answered, but why is there my contacts in Simple Contacts, but not in Simple Dialer?

**Comment by tibbi** [comment]
what contacts you mean? Shat contact source are the contact saved to? I mean the last field at the contact details screen. Does it say your email, Phone, SIM or something like that?

**Comment by SNvMK** [comment]
@tibbi umm, all contacts source is telegram

**Comment by SNvMK** [comment]
so, now i created contact in contacts, and it appeared in dialer. blah, closing
