### ISSUE TITLE
Gallery VIdeo Edit Bug

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/General-Discussion#165]
HI, thanks for all your hard work. However, there is a bug in your gallery app when trying to edit HD or 4k videos. It won't let me edit them in the folder section but will if I move them to the recycle bin.  Strange but understood. I don't want to be a bother but it is a bug and I'm in now ways a moron in tech but not shabby either. I'm running efoundation rom I flashed myself and it's understood if the bug could be because of the rom I'm running. I've seen this happen with certain apps like open source Brave on this rom but not proprietary rom. Please continue your hard work as I've seen bugs in proprietary apps too.

**Comment by GithubContributer** [comment]
Ok thanks.
