### ISSUE TITLE
Add strings for months changed by case (declension)

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/General-Discussion#168]
Hi,

In some languages (e.g. in Polish) when writing a date we are changing month name by case (declension). For example in Polish we write `4 listopada` instead of `4 listopad`. 

I think it would be good to add support for this in all apps that support showing dates with month name like Clock or Calendar. Here's a screenshot from Calendar, where it could be changed:
![image](https://user-images.githubusercontent.com/85929121/140331285-531c4f20-846f-41d3-ab5d-24a0139e1fa1.png)

And how it looks in Clock, compared to standard OnePlus Clock app (bottom of the screenshot):
![image](https://user-images.githubusercontent.com/85929121/140331379-f1645828-8cbe-495c-8158-3ca5e117f614.png)

**Comment by tibbi** [comment]
it is already reported in Simple Calendar, just add it at Simple Clock if it isnt there yet. I cant fix them together in Simple Commons or so, it will need individual approach. Thanks
