### ISSUE TITLE
can't read incoming SMS?!

### ISSUE THREAD

**Issue by milka7774** [SimpleMobileTools/General-Discussion#170]
Hi, thkns for your job. I have a Xiamoi xt10 phone.
I used Ur app with no ptoblem à thé beginning. After a while, i got a problème. I Can send SMS but can't receive thèm. I know that because i have spoken with 2 différent people who told me they had sent me text messages... I have Nevers receiived them..
Thks for your help

**Comment by tibbi** [comment]
this is the wrong repo for this, it is already reported at https://github.com/SimpleMobileTools/Simple-SMS-Messenger
