### ISSUE TITLE
Simple Rotation Control ?

### ISSUE THREAD

**Issue by Siltaar** [SimpleMobileTools/General-Discussion#173]
I'm an F-Droid user only since 2016.

Recently I had to install Rotation Control from Aurora Store, because my device is center-bottom plugged to charge and I need to charge it during OSMand-lead driving sessions, with the device settled in a plain-bottom cradle.

Previously I used the Xposed framework to rotate the screen upside-down, but lastly it failed to install.

I would loved to find a Rotation-control like app in F-Droid, and Simple Mobile Tools could be a vector for it :-)

**Comment by tibbi** [comment]
such things should be handled by the system too, not an app
