### ISSUE TITLE
Wish-list: Simple AOD

### ISSUE THREAD

**Issue by Siltaar** [SimpleMobileTools/General-Discussion#174]
I found no working AOD app in F-Droid. There are 2 of them, but none that effectively allow me to know if I received a message or not, without pressing a button.

Both have an ambiant mode that should display newly arrived notifications, but in practice I have to unlock the device to stumble upon them.

I would love a working Simple Always-On Display. (not easy with stock Samsung Oreo devices, but eh, it's a wish-list ^_^).

**Comment by Siltaar** [comment]
Because low-end OLED Samsung devices don't have notification LED…

**Comment by tibbi** [comment]
such things should be handled by the system, not any app
