### ISSUE TITLE
date format doesn't change

### ISSUE THREAD

**Issue by MarkoIndaco** [SimpleMobileTools/General-Discussion#176]
Hi, as the topic title the data won't change. I chose "15 February 2021" but even trying other format don't works. The date is always with underscores, like "2021_15_2"
I'm on Xiaomi Mi 9 Lite - crDroid 7.5

**Comment by tibbi** [comment]
Which ap you mean at all?

**Comment by MarkoIndaco** [comment]
Uh sorry :grin:  I'm taking about Simple Voice Recorder

**Comment by tibbi** [comment]
right, that setting isnt about the filename itself, just about how is the date and time interpreted at the player tab, below the filename
