### ISSUE TITLE
Editor feature requests 

### ISSUE THREAD

**Issue by Indubius** [SimpleMobileTools/General-Discussion#177]
Hi there and thank you so much for your simple apps! I love all of them and use many, most frequently the pro gallery.
In the gallery's editor, I do miss features I thought it had before: Painting (filled) rectangles, arrows and circles.
Am I missing out sth or could you implement those features, please?

**Comment by tibbi** [comment]
the current advanced editor isnt developed by us, but by a third party group of developers. Anyway, such things should be reported at the gallery section at https://github.com/SimpleMobileTools/Simple-Gallery , this one is for bugs affecting multiple apps
