### ISSUE TITLE
Font size mis-adjustment to screen size

### ISSUE THREAD

**Issue by cassio-tav** [SimpleMobileTools/General-Discussion#178]
See the screenshot

*The bug:* the App should be responsive and adapt without user intervention.

*The feature request:* aside from responsiveness,  it would be nice if the user could set font preferences (family, size…)![Screenshot_2022-01-27_12-27-45.png](https://user-images.githubusercontent.com/48675234/151392875-aecfc0d5-12d1-4a9b-bce3-e96896d0ec9f.png)

**Comment by tibbi** [comment]
Simple Clock has been abandoned already, please use an alternative

**Comment by cassio-tav** [comment]
> Simple Clock has been abandoned already, please use an alternative

In that case there should be some kind of warning in the App's description on F-Droid.

**Comment by tibbi** [comment]
yes, there is

**Comment by cassio-tav** [comment]
> yes, there is. People just dont read descriptions.

Sorry -- I do read, and I did. There's not a hint of a warning.
See attachments

![photo_2022-02-07_17-04-57](https://user-images.githubusercontent.com/48675234/152863385-d6567738-6bfb-49a0-a9ff-30f9319fd0c9.jpg)
![photo_2022-02-07_17-05-33](https://user-images.githubusercontent.com/48675234/152863389-36142ea4-3eb3-4a2b-8db1-69004ae51e92.jpg)
![photo_2022-02-07_17-05-44](https://user-images.githubusercontent.com/48675234/152863391-bddd497c-2ab8-44c2-b928-e6bc7c7fde29.jpg)
![photo_2022-02-07_17-05-53](https://user-images.githubusercontent.com/48675234/152863395-1acd0a3e-c7fa-417c-8f89-99c08445d09f.jpg)

**Comment by tibbi** [comment]
Im not sure how does f-droid updating work, it is there on the website

**Comment by cassio-tav** [comment]
> Im not sure how does f-droid updating work, it is there on the website

Well, I don't have the technical background to figure out how the information gets from your website to the F-Droid's app description. All I could do (and did) was informing you that the relevant information is not there.

Anyway, thanks for your explanation.
