### ISSUE TITLE
Custom F-Droid repo

### ISSUE THREAD

**Issue by ccptr** [SimpleMobileTools/General-Discussion#179]
This is a request for you to create your own F-Droid repo. I like to receive apps directly from the developers with an original signature, as it greatly improves security. It also allows for faster updates, as it doesn't have to be built by F-Droid or go through Google's review process.

**Comment by tibbi** [comment]
F-droid has the official apps submitted by us, doesnt make much sense to have an own repo

**Comment by ccptr** [comment]
I disagree. It greatly improves the security by removing trust in a third party. Your apps on the official F-Droid repo are built and signed by F-Droid, which means you have to trust the people at F-Droid and their security practices as much as you trust the developers of the app(s) themselves. Maybe you don't want the maintenance of your own F-Droid repo, but to say it doesn't make sense is naive IMO.

**Comment by Gamer750** [comment]
> F-droid has the official apps submitted by us, doesnt make much sense to have an own repo

If there is custom F-droid repo we could get app update more quickly than F-droid
