### ISSUE TITLE
Extending themes from the Material Components themes

### ISSUE THREAD

**Issue by proletarius101** [SimpleMobileTools/General-Discussion#180]
Simple apps are still [using the ancient AppCompat themes as the base themes](https://github.com/SimpleMobileTools/Simple-Commons/blob/3bbf37c7f947328f3d03dd4940241bafb967c5cd/commons/src/main/res/values/styles.xml), which makes the apps look old. Since they are already using the material theme library, they should base their themes on the Material Components themes as described in https://m3.material.io/libraries/mdc-android/getting-started. That would make the app appearance much improved.

I would love to make a PR for doing so, if you agree.

**Comment by tibbi** [comment]
I dont plan changing it, Android 12 is still way too new and the colors arent nice at all

**Comment by proletarius101** [comment]
How about material design 2? https://material.io/develop/android/docs/getting-started

**Comment by proletarius101** [comment]
They are not. e.g. the appearance of text fields, menus, and buttons, although they are more similar than they from MD3.

I believe `the efforts of changing only lines of code` < `much improved appearance`. Also, I'm proposing I can help with that change. The only thing that you need to measure "worth" or not is the work you need to review. But lines of code only need minutes to review.

**Comment by proletarius101** [comment]
Also, if it's MD3, you may only enable it by default for Android 12+

**Comment by tibbi** [comment]
well, you can create a pull request with what you are suggesting, but I cant promise it will be accepted

**Comment by tibbi** [comment]
What I would prefer doing instead is fetching the Accent color from the system on Android 11+ or so, but I havent been researching it yet how to do it. For now I just added auto toggling between light and dark mode.

**Comment by proletarius101** [comment]
That is exactly what the M3 themes do. You won't see drastic changes.. you may simply download the Catelog demo app and see: https://github.com/material-components/material-components-android/releases/tag/1.6.0-alpha02

**Comment by proletarius101** [comment]
So after some investigation, I can propose a PR that only change the base theme. 
- Almost no visible changes before we replace those legacy components with new ones, which can be implemented in the future.
- Both the M2 and M3 themes inherits the AppCompat base theme.

Given so,

- Will you accept such an initial PR?
- Do you want it inherit the M2 base theme or the M3 one? Only the latter can help introducing dynamic colors in the future.

**Comment by tibbi** [comment]
I dont know what changes you mean, I dont want to change anything in the default behaviour.

**Comment by proletarius101** [comment]
In the 1st phase, I'll only change https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/res/values/styles.xml and no visual changes will be introduced

**Comment by proletarius101** [comment]
Visual changes can be opt-in but they will only be in future phases

**Comment by tibbi** [comment]
well you can try changing it so I can test it

**Comment by tibbi** [comment]
Material You has just been added, it will eventually reach all apps
