### ISSUE TITLE
Giving

### ISSUE THREAD

**Issue by GithubContributor832** [SimpleMobileTools/General-Discussion#182]
I haven't spent a lot of time fishing through your sites. But where is the best place I can give by PayPal to you as I know I've slammed you with bug reports and some enhancements based off my opinion? You work really hard and please me private.

**Comment by tibbi** [comment]
it is really easy to find on the website, at https://simplemobiletools.com/donate . Thanks

**Comment by GithubContributor832** [comment]
Thanks sounds good. I actually fished through your site last night and gave it was right in front of my face.
