### ISSUE TITLE
Pause and close recording makes app crash

### ISSUE THREAD

**Issue by MarkoIndaco** [SimpleMobileTools/General-Discussion#183]
Hi, as the title I notice this issue yesterady. Step to reproduce:
1 - Start recording
2 - Pause the recording
3 - Close the recording

If you try instead to _pause - unpause - stop recording_ then it stops and save the file properly.
Well, nothing crititcal, just to inform.

crDroid 7.5 (Android 11 based)

**Comment by tibbi** [comment]
you mean at the voice recorder? Report it at https://github.com/SimpleMobileTools/Simple-Voice-Recorder please, this place is for reportings bugs affecting multiple apps

**Comment by MarkoIndaco** [comment]
(moved [here](https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/105))
