### ISSUE TITLE
White icon

### ISSUE THREAD

**Issue by julianfairfax** [SimpleMobileTools/General-Discussion#188]
Currently it's not possible to set the icon colour to white. It would be nice if this was added, as it would blend in well with GrapheneOS system apps and other apps. Thank you for making these apps!

**Comment by tibbi** [comment]
it isnt really on the roadmap, should be possible to do with new Android 13 icons

**Comment by julianfairfax** [comment]
> it isnt really on the roadmap, should be possible to do with new Android 13 icons

May I ask why it isn't? For operating systems such as GrapheneOS, it'd make it possible for the apps to blend in perfectly with the stock apps. And will those Android 13 icons be compatible with Android 12?

**Comment by tibbi** [comment]
because if the background is white, we would have to change the foreground color too and that would create many new color combinations that would further increase the app size

**Comment by julianfairfax** [comment]
> because if the background is white, we would have to change the foreground color too and that would create many new color combinations that would further increase the app size

Can't you only change the foreground colour to black when the background is changed to white rather than creating any more new colour combinations? I don't know how you've done it but if the icon is an svg then recolouring it should be easier?

**Comment by tibbi** [comment]
I dont want to add a color combination like that. And icons cannot be generated dynamically.

**Comment by julianfairfax** [comment]
Could you help me add it to my fork? So far I've got it to be the system icon (not the launcher default), and the option shows up in the settings, but clicking on it crashes the app. Here's what I'm working with: https://github.com/julianfairfax/Simple-File-Manager and https://github.com/julianfairfax/Simple-Commons

**Comment by tibbi** [comment]
first you should check if your launcher doesnt support custom icons, that should be easier. Long press the icon to see what options appear.

**Comment by julianfairfax** [comment]
It does. It works when I select other colours in the app settings. It just seems I haven't made all the required changes to the simple commons repo yet.

**Comment by julianfairfax** [comment]
When you have some time, could you take a look at https://github.com/julianfairfax/Simple-File-Manager/commit/f9a191b7bb61f35e5b76105f4a773485914bbd2a and https://github.com/julianfairfax/Simple-Commons/commit/d6e6f7511f11d40788fbff452757a86f5b333c62 to see what I'm missing? As I said before, the white colour option is visible in the icon colour settings dialogue, but when I select it, the app crashes.

**Comment by tibbi** [comment]
what does the crashdump say?

**Comment by julianfairfax** [comment]
> what does the crashdump say?

How would I obtain that?

**Comment by julianfairfax** [comment]
> well, how have you ran the code? Not in Android Studio? Those are basic things though, I dont really want to reach Android development here.

I built it and then ran it on my phone. I'll attempt to get a crashdump from there or run it in Android Studio. I would've thought it'd be easier for you to see what I got wrong with my commits than for me to, since you accurately mention how this is basic, and I'm clearly not good at it.

**Comment by julianfairfax** [comment]
I have managed to get it working now. My apologies for bothering you with this
