### ISSUE TITLE
Backup settings to file 

### ISSUE THREAD

**Issue by girlmaya** [SimpleMobileTools/General-Discussion#192]
I use SMT across multiple devices and would appreciate if the apps saved the settings in a folder so i could sync the settings between devices. I know Gallery has a manual settings export and i'm not sure which other SMT apps have the same functionality. Files does not.

In my case, I wish to be able to change any setting on one device and see the same change reflect on other devices as soon as Syncthing updates the files

Thanks

**Comment by tibbi** [comment]
exporting settings from all apps is already reported somewhere, but dont expect automatic settings applying from some file
