### ISSUE TITLE
No more changelogs on F-Droid

### ISSUE THREAD

**Issue by ltGuillaume** [SimpleMobileTools/General-Discussion#193]
Is the removal of changelogs on F-Droid by design? If so, what's the reason for it?

**Comment by tibbi** [comment]
ye, I moved the app metadata like app title, short and long description into separate Weblate components so that they can be kept up to date with the Google Play versions through fastlane, ensuring better translations there. Sadly I couldnt exclude changelogs there so with the old system the volunteering translators would keep translating the changelogs too unnecessarily, as they wouldnt be shown to anyone anymore. Too many strings could discourage new people from translating the important strings too.

**Comment by ltGuillaume** [comment]
...and there's no way to extract the data for F-Droid? I know you did the split (and I'm just seeing the move failed for SMS Messenger, at least for Dutch), but I don't really understand why it would then be impossible to have the changelogs show up on F-Droid.

**Comment by tibbi** [comment]
because changelogs are a part of the app metadata, like the short description etc

**Comment by ltGuillaume** [comment]
Sorry, but I have no clue what you mean. You're using fastlane, so what keeps you from adding the changelogs to `fastlane/metadata/android/en-US/changelogs`? Why would that have anything to do with how you set up Weblate? You still need to put the `full_description.txt`, `short_description.txt`, `title.txt` in there, which come from the metadata you moved, so what's different for the changelogs?

**Comment by tibbi** [comment]
weblate fetches everything inside fastlane folders, so the changelogs would be offered for translating too

**Comment by tibbi** [comment]
changelogs would really discourage new translators as they increase the word counts

**Comment by ltGuillaume** [comment]
I get that, and so you can state those don't need to be translated. There might finally be an option in Weblate to disable translation by now.

I'm just saying, I think it's better to instruct a few translators that changelogs don't need to be translated than to hold back some vital information about the changes in your apps from end users.

**Comment by tibbi** [comment]
F-droid has a Changelogs section, so if someone wants to read it, it is really easy to find

**Comment by ltGuillaume** [comment]
No one will open up a separate page every time an update has been released, _especially_ when they used to get the changelog for those apps inside F-Droid.

**Comment by ltGuillaume** [comment]
For reference, other users: https://teddit.net/r/SimpleMobileTools/comments/vvt3r3/fastlane_changelogs_deleted/

**Comment by ltGuillaume** [comment]
By the way, are the instructions to the likes of

> If you do not want to do it, you can also go into your device Settings - Apps - Special app access - Media management apps and allow this app to manage media.

still accurate for your devices?

For my device (Android 11), this won't do. I need to follow one of the following paths to set the permission:

1. Long-press app's icon -> App info -> Permissions -> Files and media
1. Settings -> Apps and notifications -> Permission Manager -> Files and media -> This app

Then Allow access to media only (or Allow management of all files)

**Comment by tibbi** [comment]
Media Management app is available on Android 12 only

**Comment by ltGuillaume** [comment]
Ah ok, thanks for explaining. Haven't check on an Android 12 device yet.

**Comment by tibbi** [comment]
that whole thing is a big mess that keeps changing with every OS version and there will be some new media file permission changes with Android 13 again...

**Comment by tibbi** [comment]
things keep getting stricter and apps have always less access to the device storage etc which is not necessarily a bad thing, but it means that we have to keep removing features and keep getting bad reviews for it

**Comment by ltGuillaume** [comment]
I'd like to revisit this for the following reasons:

- Weblate has an add-on called `language_regex` by which you can exclude translations from being presented to translators.
- It makes less sense to offer Play Store users changelogs (as those people just turn on auto-update and never get to see them anyway), instead of F-Droid users (who update manually, are generally much more conscious about what is happening on their device and are more interested in app development and keeping up with changes that caught their eye).

**Comment by tibbi** [comment]
I dont see such an addon, how can I enable it?

**Comment by ltGuillaume** [comment]
Sorry I misunderstood the sentence about it in the FAQ. It's part of `weblate.discovery.discovery`. See https://docs.weblate.org/en/latest/admin/addons.html

**Comment by tibbi** [comment]
right, I see. Do you know what exactly should be filled out there to make it work well?

**Comment by ltGuillaume** [comment]
I think the following is the best way to go:

https://docs.weblate.org/en/latest/formats.html
>In case you don’t want to translate certain strings (for example changelogs), mark them read-only (see [Customizing behavior using flags](https://docs.weblate.org/en/latest/admin/checks.html#custom-checks)). This can be automated by the [Bulk edit](https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-flags-bulk).

https://docs.weblate.org/en/latest/admin/addons.html#id2
> Marking all changelog strings read-only
Search query | language:en AND key:changelogs/
-- | --
Translation flags to add | read-only

**Comment by tibbi** [comment]
oh gosh, they really arent making it easy. Anyway, Ill take a look at it before updating some app, thanks.

**Comment by ltGuillaume** [comment]
After Chocolatey, the Weblate documentation must be the messiest and most incomplete I've ever seen. What a mess...

**Comment by tibbi** [comment]
guess I managed fixing it automatically by adding the "language:en AND key:changelogs/" bulk edit rule for adding read-only flag (note to myself), will see soon if it works

**Comment by ltGuillaume** [comment]
Cool, looking forward to it!

**Comment by ltGuillaume** [comment]
Today, I saw a changelog for Simple Tank You in F-Droid! The latest update for Simple Galery was built on the same day, but it didn't have a changelog yet. Perhaps the next build.

**Comment by tibbi** [comment]
contacts has it at https://f-droid.org/packages/com.simplemobiletools.contacts.pro/ , added it wrong to the gallery. Future releases will have it though unless I forget adding them. All apps have been updated recently, so they will have it.

**Comment by ltGuillaume** [comment]
Thank you so much! 😃
