### ISSUE TITLE
Add the possibility of using another color than primary for the top bar background

### ISSUE THREAD

**Issue by Hunter16g** [SimpleMobileTools/General-Discussion#194]
I like to have black backgrounds whenever possible, however ATM it's not possible to set it for the whole screen because primary color is used for the background of the top bar. I also feel it's a bit counter-intuitive to use one color setting for both foreground elements in the app and background.

Just to avoid ambiguity, I'm talking about the blue background here :

![Screenshot_Calculator](https://user-images.githubusercontent.com/15839619/180776812-7c39154f-f863-4975-91db-255c04de39e4.png)

**Comment by tibbi** [comment]
that isnt on the roadmap

**Comment by Imy367** [comment]
#194

пн, 25 июл. 2022 г., 20:24 Tibor Kaputa ***@***.***>:
