### ISSUE TITLE
Weblate user "Worldfast" is a bot, please revert all translations

### ISSUE THREAD

**Issue by ltGuillaume** [SimpleMobileTools/General-Discussion#195]
The user "Worldfast" is a bot and has been poisoning the translations of SimpleMobileTools. See https://hosted.weblate.org/user/Worldfast/

Does Weblate give you the tools to revert all translations by a single user in all your projects in one go?

**Comment by tibbi** [comment]
it is a freelancer with many colleagues that I ordered some translations from, not a bot

**Comment by ltGuillaume** [comment]
So they translate lots of strings of loads of different languages, without actually knowing what it is translated into (they're machine translations), _even though the strings were already properly translated_?

**Comment by tibbi** [comment]
I told them not to edit translated things, maybe someone was hyperactive
