### ISSUE TITLE
Simple app threat model

### ISSUE THREAD

**Issue by sparagi** [SimpleMobileTools/General-Discussion#197]
I would like to create and publish a threat model for one of your apps.  I have several related questions:

- Would that be OK?

If so:
- I was considering Simple Gallery.  Is there a different app you would prefer?
- Would anyone from the development team like to participate, and if so, how (see some options below)?
- Where/how would you like me to keep you posted about my progress?

# Proposal

Here is more background and detail regarding this idea:

I am one of the authors of the Trike threat modeling methodology, and I am trying to update the publicly available documentation for the method and eventually port and release an updated open source tool.  I have plenty of confidential threat models for my clients, but I would like to work several small examples of different types that I can publish, and use in my test cases for the new tool.  I would prefer to use a real example that I am familiar with, and I'd like to contribute to an open source project.  I have been a fan of Simple Mobile Tools since I switched to Android a few years ago.

I would create:
- A set of security objectives (that you choose, if you want to participate yourself; I would walk you through the process)
- Security analysis of the design of the security-relevant functions of the app, and how well it meets those objectives
- Any diagrams and design notes I need (or you can do this to answer my questions, if you want)
- Bug reports for any issues I discover

I would like to post the security objectives and analysis as an example on [the Trike web site](https://www.octotrike.org/), with enough context from your design documents for them to make sense.  You are welcome to use any or all of what I produce in your materials as well; I was thinking of a CC-BY license on the threat model.  My guess is that any published, free example of a Trike threat model would soon start showing up in multiple threat modeling training courses and guides.

This would be my first published threat model of an open source system, so I don't have an established process for working with an open source project.  Since I would be creating the model in my spare time after my billable work, this would probably be spread over a few months.  I could do some mix of these things:
- My usual meeting-based process that I would use with a corporate client (maximum of an hour or two of meetings for you per week)
- Proceed mostly on my own using the published documents and source code to infer answers to my questions
- Ask questions on Telegram or any other location you prefer
- Send you intermediate pieces for review as I get them done

I'd love to offer to let you shadow me through the whole process if you want to learn how, but because this is the first publishable example in a long time and there are a lot of process updates that haven't been publicly documented yet, that isn't a realistic option.  If you want to shadow, I could approach some other project first and come back to you.

No matter what I do, I will follow the project's process for reporting security issues.  I want to publish this model eventually, but I am not on a fast timeline here, and I will do my utmost to avoid dropping 0-days on open source projects.  And, if I find a previously unmitigated design flaw and you mitigate it, I will update my copy of the threat model to reflect the mitigation.

Finally, if I/we do this, you have no obligation at all to provide it, but I'd be very interested in your feedback about pretty much anything associated with the methodology, the process, the results, or anything else about Trike as you experience it.  Development teams at my corporate clients often have incentives to go along with whatever I say.  Therefore, I would probably hear about results that were hard to apply, but not always why it was hard, and I probably wouldn't hear if developers' experience could be more pleasant.  So, your feedback would be especially valuable to me.

**Comment by sparagi** [comment]
To clarify, the version with lots of meetings would be about 4 hours total, spread over a couple of months in this case.

**Comment by tibbi** [comment]
thanks, but currently Im not interested

**Comment by sparagi** [comment]
Thanks for getting back to me, I appreciate it and your apps!
