### ISSUE TITLE
Internationalization issue at Weblate

### ISSUE THREAD

**Issue by meskobalazs** [SimpleMobileTools/General-Discussion#198]
I started to take up doing translations again, and I saw that new strings are not actually untranslated at Weblate, but they are copied from the English source strings. This looks like an issue with the I18N setup of the projects.

Currently I am able to fix these, but this is not ideal, as it breaks my usual translation workflow, i.e. downloading untranslated strings in a PO file.

**Comment by tibbi** [comment]
strings are taken from the Android projects files, so they have to use the english version. I dont want to have missing strings in any language

**Comment by meskobalazs** [comment]
I did not react because I was not familiar with Android's translation system at that time, but this is just not true. You don't need to have all keys in every file, if something is missing from `values-hu/strings.xml`, it will use the `values/strings.xml` file as a fallback, so there is no issue whatsoever.

And to be clear, it's not just that I find this annoying, I've missed translation work, because it said it was 100% translated, while it wasn't.
