### ISSUE TITLE
Improve launcher names

### ISSUE THREAD

**Issue by kTyn9A9Kw3** [SimpleMobileTools/General-Discussion#2]
Good idea opening this repo, I'll "migrate" my suggestion to here.

So as I suggested on the other issue, I think it would be better if app launchers would be named by their function (eg: Gallery instead of Simple Galllery). The reasons are:
1- Better presentation. Too much "Simple" repetitions cause some weirdness when looking to the app list.
2- Better for translations. Launcher names could be translated to different languages, which makes sense for SMT since it's intended to be replacements for stock apps and general utilities.
3- Better for everyone. Reasons 1 and 2 can make the experience of replacing stock and proprietary apps with open source apps easier for old persons, non english speakers and kids.

To help you I already did a pull request with the changes on strings.xml files, that should change the launcher names. The app names (displayed on Settings -> Apps and Playstore?) should remain the same, unless you also use the string for that propose.

Note that I researched with care and tried to translate everything correctly, still the original translators should review. I noticed some strings added on recent commits aren't translated yet, so a revision will be needed anyway.
I only used Google Translate for words I couldn't find any reference on Wikipedia or other websites.

References:
[not needed]

**Comment by tibbi** [comment]
I might rename them as I will be updating the apps with new launchers. 
Why did you keep creating new strings.xml files tho? None of the pull requests can be merged as they have conflicts.

**Comment by kTyn9A9Kw3** [comment]
Yea I'm a bit noob on Github sorry, I wanted to update my fork but I guess it has to be done manually.
Luckily you found a better way, I already have the new Gallery and looks much better (but seems the app name on F-Droid and Settings page is the same as the launcher name, you might need to check that).
With the icons polishing it will definitely make the app collection look "fresh" while keeping the KISS philosophy :)
Thanks for listening our suggestions

Cheers

**Comment by tibbi** [comment]
I wrote a small guide about how to post file edit suggestions (Pull requests) easily. You dont need to create forks and mess around with git, just click it out via github. Its at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file

**Comment by kTyn9A9Kw3** [comment]
Thanks very useful, but that method will fork the repo anyway but "on the background" (atleast it says "fork this project and edit/delete the file"). The issue was my repo was too outdated and I had to update it somehow.
Btw all apps look great :) this issue can be closed I guess
