### ISSUE TITLE
Setup continuous deployment

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/General-Discussion#20]
Having auto-deploy on commit set up allows everyone to test and review changes immediately instead of waiting for a release or building from source.

**Comment by tibbi** [comment]
a new version after every couple commits would really spam the users

**Comment by trubitsyn** [comment]
You misunderstood me. Continuous deployment means CI service is set up (e.g. Travis CI) which builds an artifact after each commit and runs tests on it. It does _not_ get released.

**Comment by tibbi** [comment]
aha, well I dont have tests anyway, i dont think its needed. The apps are simple so they are usually compilable after every commit.

**Comment by trubitsyn** [comment]
Ah, okay. Btw, I was wrong saying "Deployment". I should have said "Delivery". My bad.
