### ISSUE TITLE
System Default does not seem to use right color scheme

### ISSUE THREAD

**Issue by SnoutBug** [SimpleMobileTools/General-Discussion#201]
The headerbar and navigation bar seems to be using `system_accent2_800` as color, while other m3 apps seem to use a different style. i'm not sure what color would be the right one to use.
Also the action buttons, for example the add contacts button in contacts seems to be using inverse primary. I would expect container or secondary

**Comment by tibbi** [comment]
there is no proper color to use, every app can decide on its own

**Comment by SnoutBug** [comment]
> Google apps are not consistent **either**

I never said the design is not consistent. But since you feel like your apps aren't, why don't you strife towards more consistency? 

> there is no proper color to use, every app can decide on its own

I agree with you on that one, but you will achieve objectively better results when sticking closer to the [m3 guidelines](https://m3.material.io/styles/color/the-color-system/color-roles). I had the feeling that you want to have a simple, yet beautiful looking suit of tools, that work, and look well on every device (why else would you bother adding this amount of visual customization?) so why stop here?

**Comment by tibbi** [comment]
We are using those material colors already. And our apps are consistent with each other, unlike the Google ones.

**Comment by SnoutBug** [comment]
> We are using those material colors already. And our apps are consistent with each other, unlike the Google ones.

That's undeniably true. But yet I would love to see the apps being consistent with other apps using the m3 design scheme, like io.github.muntashirakon.AppManager, Vanadium, the GrapheneOS PDF viewer or Lemuroid. I think it would be great to see them all fit together nicely.

**Comment by tibbi** [comment]
ye, we plan doing some materialish redesigns soon. Nothing too drastic, just step by step as usually
