### ISSUE TITLE
Simple Phone

### ISSUE THREAD

**Issue by ZarVladimirII** [SimpleMobileTools/General-Discussion#202]
Hello Tibbi,

interesting you´re going to support a whole OS and Hardware.

But looking around for some information I´m worrying because it looks more suspicious then trustworthy.
Getting a complete hardware design created and produced is huge. For transparency you should clearify how you got it.
What I know by now there are at least 2 other companys selling the same hardware, all claming to focus on privacy.

If it would be clear that 'Simple OS' is based on https://en.wikipedia.org/wiki//e/_(operating_system) it would be a lot lot better. They have proven who and what they are.
Lunar and The Good Phone Foundation haven´t.
And [this ](https://www.notebookchat.com/index.php/topic,155902.0.html?language=german-utf8)is already out there.

Have a nice day.

**Comment by tibbi** [comment]
Hey, you can already find some aswers at https://simplephone.tech/faq/ . More info about SimpleOS and GoodPhone foundation will be released soon.
