### ISSUE TITLE
Add Simple-CodeEditor add for editing small scripts conveniently 

### ISSUE THREAD

**Issue by EmilySeville7cfg** [SimpleMobileTools/General-Discussion#204]
I expect the following features from such app:

- Regex based syntax highlighting like in Nano
- Builtin support for the most popular languages
- Tabs
- Theming support like in all Simple apps
- Support for a horizontal orientation (some editors lack this feature

Below I described a little bit more details about how some editor features could work.

# Regex based syntax highlighting

For such purpose JSON-based config can be used with the following syntax:

```
{
  "{{color-name}}": ["{{keyword-patterns-to-highlight}}"]
}
```

for instance:

```json
{
  "red": ["^(begin|end)$"]
}
```

The reason why I suggest JSON based format is I can create JSON schema for it later and propose to [SchemaStore](https://github.com/SchemaStore/schemastore/pulls) to validate such configs. ;)

**Comment by tibbi** [comment]
thanks, but such an app isnt really on the roadmap :)

**Comment by EmilySeville7cfg** [comment]
Can u share your roadmap then? ;)

**Comment by tibbi** [comment]
I cant, it is in my head
