### ISSUE TITLE
Feature Request: Improved App Theming Consistency

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/General-Discussion#206]
Currently, not all Simple apps respect every aspect of the Shared Theme, most critically, the Bottom Navigation Bar Color.
![Screenshot_20221207-000532.png](https://user-images.githubusercontent.com/19295950/206093222-a2082360-cee7-41a7-ac41-d647ecd422ec.png)

Apps that fully respect Shared Theme: 
- Calculator
- SMS Messenger
- Calendar
- Thank You
- Draw
- Flashlight
- Notes

Partially respect Shared Theme:  
- Gallery (translucent nav bar in media view is black/white only)
- Keyboard (only in settings, otherwise black/white)

Don't respect Shared Theme:  
- Clock
- Camera
- Music Player
- File Manager
- Contacts
- Dialer

**Comment by tibbi** [comment]
some ui related improvements including the bottom navigation are on the roadmap. If there are tabs at the bottom, it has to work differently.
