### ISSUE TITLE
App Inquiry: Email Client

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/General-Discussion#207]
Thinking about my usage patterns and the Simple Apps suite, I think a Simple Email would be great and fill a big void where I spend a ton of time.

A potential candidate for this could be K9/Thunderbird Mobile, and essentially make a UI fork that follows Simple Theming and interoperates very tightly with the Simple apps (contacts, calendar, Dialer, notes, drawing, gallery, files, voice recorder, camera, etc).

The rest of the Simple Suite fill out the functions of a pretty great PIM ecosystem... All that is missing is an email client to link them all together easily.

**Comment by tibbi** [comment]
it doesnt fit into the suite, so dont expect having it
