### ISSUE TITLE
Weblate suggestions

### ISSUE THREAD

**Issue by gallegonovato** [SimpleMobileTools/General-Discussion#209]
Good afternoon @tibbi

First of all wish you A HAPPY NEW YEAR 

I would like to propose you a suggestion for weblate. Since I noticed in the translation strings of the applications: video.txt:1

I would like to propose that they should be marked as hidden or not to translate. Since I noticed that in other languages they put spaces. And weblate puts it as correct.

And once you had told me not to put anything.

That's why I don't know what you think of my idea, and so it doesn't come out as untranslated?

Thanks for your help and time.

**Comment by tibbi** [comment]
Hey, theres no hiding, I made the video string in App Launcher forbidden, check how it works

**Comment by gallegonovato** [comment]
Good afternoon:

I will have a look.

Please don't take this suggestion wrong. But I noticed in 

https://hosted.weblate.org/translate/simple-mobile-tools/simple-thank-you-metadata/es/?q=check:translated#translations

https://hosted.weblate.org/translate/simple-mobile-tools/simple-notes-metadata/es/?q=check:translated#translations

For example there were languages like Polish or Ukrainian that put a space and an enter. And I thought it was good Weblate.

A hug

**Comment by tibbi** [comment]
ye, it seems to cause errors at fastlane updating too, but Im not sure what is the best way of hiding it. Weblate is quite difficult to use.

**Comment by tibbi** [comment]
the max-length flags keep being ignored too at title, short and long descriptions :/

**Comment by Aga-C** [comment]
> I made the video string in App Launcher forbidden, check how it works

Change from `fobridden` to `read-only`.

**Comment by tibbi** [comment]
it already had the `read-only` flag, but looks like it was applied to the english string only, not the other languages.. what a mess

**Comment by Aga-C** [comment]
@tibbi Now it works :)

**Comment by tibbi** [comment]
ok, applied it to all languages now, will see how it works. Thanks

**Comment by gallegonovato** [comment]
Good afternoon @tibbi and @Aga-C

First of all I apologize for taking so long to reply, but here because of the bad weather a node that supplied Internet to where I live got screwed up. And I was left without connection.

Thank you for your help and time. 

It seems to be working fine now but I'm still in flashlight. The rest is great.

I was also seeing that in the Calendar in the description it says for 2022. Wouldn't it be convenient to change it to 2023. Or maybe look for a description that is valid for any year?

A hug and thank you for your kindness and time.

**Comment by tibbi** [comment]
I changed the descriptions to 2023 already, it just needs an app update to be applied to f-droid
