### ISSUE TITLE
Hidden/Locked files showing in Windows

### ISSUE THREAD

**Issue by asavalle** [SimpleMobileTools/General-Discussion#210]
Just a question. 
I have a hidden and locked folder in the Simple Gallery/Files, but when I connect to my Windows machine, the files are very much visible and unlocked. 
Is there a way to keep them hidden/locked?

I realize this may not be something you guys can address. Just thought I'd ask.

Thanks

**Comment by tibbi** [comment]
nope, this locking works in-app only, just like it is described in the app. It isnt any encryption
