### ISSUE TITLE
Feature Inquiry: Set Preferred Simple Apps for Intents

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/General-Discussion#211]
Is it possible on Android to set a preferred app to open for a given intent from within a Simple app?

For example, it'd be preferred to have Simple File Manager open when loading a file to Simple SMS as opposed to Files AOSP that came with my ROM.

Same goes for a Gallery picking intent, etc.

**Comment by tibbi** [comment]
that is handled by the system, not us. At the app picker just check the "Always" option.

**Comment by Saijin-Naib** [comment]
Done that, cleared Files AOSP as handler and still it is default for Picking intents and Gallery intents.

**Comment by tibbi** [comment]
well, on some devices it cannot be changed. Try downloading some other galleries or file managers if they work differently.
