### ISSUE TITLE
Problem with Weblate

### ISSUE THREAD

**Issue by gallegonovato** [SimpleMobileTools/General-Discussion#212]
Good afternoon:

It turns out that Weblate tells me that there is an untranslated string, but if I click on the 1 I get. It tells me that there is no string. I check all the translations, and supposedly in Simple SMS Messenger metadata there is 1 string with 17 words. 

But the same thing happens to me, I click on it and there is no string.

A big hug

**Comment by tibbi** [comment]
which string do you mean? Short description? Video.txt is always empty, only the gallery has a video there.

**Comment by gallegonovato** [comment]
Good afternoon @tibbi

Sorry for explaining myself wrong. I will try to explain myself better.

If I go to Simple Mobile Tools and then to Simple SMS Messenger metadata I get in Spanish 1 unfinished string, and 17 unfinished words.

But it comes out and comes out, but it tells me No strings found! So I do not know what it is.

I upload screenshots:

https://ibb.co/qm4mjGP
https://ibb.co/L52cRLt
https://ibb.co/5rLJ9My

A hug

**Comment by tibbi** [comment]
maybe some strings just have to be confirmed, or some warning unticked

**Comment by gallegonovato** [comment]
good afternoon @tibbi

Thank you very much for your time and help.

It must be a Weblate bug. Since today I went to Simple Mobile Tools checks and it doesn't come up anymore.

The truth a curious thing. The only thing if it comes out again I'll tell you. Because it does not occur to me that it can be.

A hug
