### ISSUE TITLE
Simple Weather app

### ISSUE THREAD

**Issue by meenbeese** [SimpleMobileTools/General-Discussion#214]
Honestly, a simple weather app would be awesome because there are not a lot of free and open source options on Android. Apps like Forecastie look outdated, and while Geometric Weather looks decent, it is not actively maintained for a long time. If you could create a really simple material designed weather app that looks like the rest of the apps, I would definitely use that. What do you think @tibbi ?

**Comment by tibbi** [comment]
nope, it doesnt really fit into our suite as it cannot work without internet access

**Comment by meenbeese** [comment]
Sad to hear that. Continue the great work!
