### ISSUE TITLE
Translation of the app names

### ISSUE THREAD

**Issue by Mr-Bajs** [SimpleMobileTools/General-Discussion#218]
Related https://github.com/SimpleMobileTools/General-Discussion/issues/36

Been doing some translation in Weblate, though i found out that also the name should be translated. I did translate the app names to swedish before i found out. But the namne i my mind should not be translated at all. It even lead me to problems finding the app though F-droid and when i found it i was very uncertain if it was the app i was looking for. And this could potentially even become a security risk and easy to expolit be having the apps going under maybe hundreds of diffrent names. It's also becomes unclear if refers to a general or default app or the app itself. 

If I found it confusing then others also will, i dont think translating the app names is a good practice and should be avoided.

If translating the app to every language 1 app could be referd to several 100 of different names, and you could always wonder if they are meaning there app or some other app.

There are short strings for the app that exclude Simple that might be translated.

**Comment by tibbi** [comment]
they should be translated
