### ISSUE TITLE
Suggestion a new Simple Mobile Tools app

### ISSUE THREAD

**Issue by RealVegOs** [SimpleMobileTools/General-Discussion#224]
It may be named - "Simple Drop Alert" - which makes use of the accelerator
sensor. Imagine you drop your phone on soft surface, gras or sand, instead
of putting it into your pocket. You don't notice and walk on. Later you miss
your phone and somebody other may find or even steal it. Simple Drop Alert
makes a yelling sound for some seconds in case the phone drops. Problem
solved!

I would like to find that app on f-droid! Thanks for any considerations and
thanks for all your other beautiful apps.

**Comment by tibbi** [comment]
such an app isnt really on the roadmap

**Comment by RealVegOs** [comment]
Sad to read! Could you please recommend somebody who may write such an app?

**Comment by tibbi** [comment]
not really, I cant. Just find some student
