### ISSUE TITLE
Add custom hex accent colors

### ISSUE THREAD

**Issue by lukasvrenner** [SimpleMobileTools/General-Discussion#227]
Currently, you can choose custom accent colors. You can also choose custom background colors. For the background colors, you are able to choose and hex color. However, for accent colors, you have to use one of the pre-chosen colors. It would be nice if one could choose custom colors. Thanks for the great project!

**Comment by tibbi** [comment]
that cannot be done as some colors cannot be changed dynamically, we had to preset some
