### ISSUE TITLE
Cleanup empty directories after move operations

### ISSUE THREAD

**Issue by resolritter** [SimpleMobileTools/General-Discussion#229]
This ticket is about empty directories lingering after move-related filesystem operations in SD cards. It is related to https://github.com/SimpleMobileTools/Simple-File-Manager/issues/426.

The situation described below happens when moving files stored in SD cards. I assume it is related to `startCopyMove` from https://github.com/SimpleMobileTools/Simple-Commons/blob/30e632159293c87137176fcb6d9b4d50c2debdee/commons/src/main/kotlin/com/simplemobiletools/commons/activities/BaseSimpleActivity.kt#L879.

# Problem

Suppose that you have the following folder structure:

```
foo
└── bar
   └── baz.txt
```

If you move `foo` to `newFolder`, you'll end up with the following structure:

```
newFolder
└── bar
   └── baz.txt
```

However, the empty folders in `foo` are not deleted after the move:

```
foo
└── bar
```

These folders should be deleted because they're empty after the move.

# Solution

After a **directory** is moved with `copyAndMove`, clean up all empty directories in its source path. I assume that this is not needed for `renameTo`.

**Comment by tibbi** [comment]
move the report into the proper repository please, this General-Discussion is about issues affecting multiple apps. A setting for deleting empty folders is already present in the gallery.
