### ISSUE TITLE
Simple Notification Shade

### ISSUE THREAD

**Issue by Secret-chest** [SimpleMobileTools/General-Discussion#230]
I just want a notification shade with a classic material design (simple circular buttons), customisable, no ads, no fuss.

**Comment by tibbi** [comment]
what do you mean, what shade?

**Comment by Secret-chest** [comment]
The notification area / quick menu you access when dragging the statusbar down.

**Comment by tibbi** [comment]
that cannot be changed by some app, it is handled by the system

**Comment by Secret-chest** [comment]
It can as long as it is an accesibility service
