### ISSUE TITLE
Automatic export of saved data in some SimpleMobile Tools apps

### ISSUE THREAD

**Issue by matusmlady** [SimpleMobileTools/General-Discussion#233]
Hello, I would like to firstly thank you for implementing the automatic export of events in the simple calendar app. I would like to suggest expanding the feature also to the simple notes app and also the contacts app. Also I would love to see an option to select how many backup files to keep in each of the apps. Thank you, appreciate the work you put in all of this, I am a daily user. Good luck.

**Comment by tibbi** [comment]
you can already do most of those..

**Comment by matusmlady** [comment]
sorry I didn't notice you can do it in the notes app. Have you given any thought on selecting the number of backups to keep?

**Comment by tibbi** [comment]
not really, I dont plan limiting it

**Comment by matusmlady** [comment]
for my use case, it is enough to keep f.e. 2 last backups, 2 just to be sure if 1 wasn't enough. what I had in mind was a slider with f.e.   1-2-3-5-10-50-100-unlimited   files to keep. right now I have 97 files that essentially contain the same data, only the later ones have more new stuff, with 8.5MB in total. it adds up quicker as new events are created xd
