### ISSUE TITLE
$15 per week to use a an open source flashlight app?

### ISSUE THREAD

**Issue by jgrimard** [SimpleMobileTools/General-Discussion#247]
$15 per week to use a an open source flashlight app?
What is this world coming to?

**Comment by inson1** [comment]
@jgrimard 
https://github.com/SimpleMobileTools/General-Discussion/issues/241
https://github.com/SimpleMobileTools/General-Discussion/issues/244

**Comment by Secret-chest** [comment]
The calendar has temu ads, 15 euro per week for colours, no ads and support?

**Comment by Jozxyqk6** [comment]
Solution: use the fossify apps from https://github.com/FossifyOrg
