### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by dfg555** [SimpleMobileTools/General-Discussion#250]
You think you're going to shove ads? Swift Backup doesn't think so!

![ad](https://github.com/SimpleMobileTools/General-Discussion/assets/33276385/76872c0e-c77d-47b7-acc9-5291282027d4)
![ez](https://github.com/SimpleMobileTools/General-Discussion/assets/33276385/a23bb6cb-9052-4ff1-849f-b21d1ee1ef2b)

**Comment by Jozxyqk6** [comment]
Alternatively, replace said applications with the fossify versions.
