### ISSUE TITLE
navigation drawer

### ISSUE THREAD

**Issue by redojg** [SimpleMobileTools/General-Discussion#32]
to switching between playlists, folders, notes

**Comment by tibbi** [comment]
I want to avoid using the navigation drawer for now, I hate that terrible element, as its hard to reach.

**Comment by redojg** [comment]
are you shure your device sensor is ok? me and many other people in the world dont have such problem. also it can be opened with button or any other way so you can keep the button showing list of notes and also add a thing which is comfortable for many people

**Comment by tibbi** [comment]
ye its an arguable topic, but I dont want to create apps which I will hate using, thats just not the way to go. Im creating apps the way Id like them to work, people will get used to whatever there is, if its good enough.

**Comment by redojg** [comment]
of course you shouldnt create apps you will hate using, i just thought you wont if usage of navigation drawer will be optional
