### ISSUE TITLE
Broken link in strings.xml comments in every app

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/General-Discussion#33]
``

The right link is `https://github.com/SimpleMobileTools/Simple-Commons/tree/master/commons/src/main/res`

**Comment by trubitsyn** [comment]
I found it here: [https://github.com/SimpleMobileTools/Simple-Notes/blob/master/app/src/main/res/values-ru/strings.xml](url) but I suppose there's more than one, because every app has such comment.

**Comment by tibbi** [comment]
ah ye, could be. Some pull requests would be appreciated ;)
