### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by Phoenix1747** [SimpleMobileTools/General-Discussion#35]
No ads, no unnecessary permission, simple and do what they should - no more and no less. You apps are awesome, thanks!
![T.Hanks](https://img.memecdn.com/THanks_fb_28684.jpg)

**Comment by tibbi** [comment]
heh, thanks :) There's still a long way to go before taking over the playstore with billions of downloads.

**Comment by Phoenix1747** [comment]
Oh well, but hey none of your apps has less than 4.1 stars at the Play Store. That's a very solid base to start from ;)

**Comment by tibbi** [comment]
yea, considering that even the oldest apps are just 17 months old and it was a hobby project, it's not bad. Now Im going to work on the apps fulltime already, so things should speed up.

**Comment by Phoenix1747** [comment]
Oh nice, sounds good!
