### ISSUE TITLE
App names Play Store

### ISSUE THREAD

**Issue by Phoenix1747** [SimpleMobileTools/General-Discussion#36]
Do you really want the app names like "Simple Camera" translated to different languages? I think that the original title sounds much better in some cases than e.g. the German translation. Not least because your company name's Simple Mobile Tools which would show the connection to all the apps.

**Comment by tibbi** [comment]
Im not sure about what I want here, or what is the general user experience since Im using english devices. "Simple" is not a brand like "Google" or so, so I think it should be translated. There's honestly not too many things that sound well in German :p

**Comment by Phoenix1747** [comment]
Haha seems quite accurate. Ok so you'd simply (no pun inteded) translate it?

**Comment by tibbi** [comment]
ye, let's translate it
