### ISSUE TITLE
FR: Include metadata for fdroid

### ISSUE THREAD

**Issue by mueller-ma** [SimpleMobileTools/General-Discussion#37]
When providing metadata via a fastlane directory, fdroid automaticly shows them in the store. You dont need to install fastlane, just create the folder

Example: https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android/en-US
Info: https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots

**Comment by tibbi** [comment]
I dont understand what you mean. I should create the fastland directory for some reason?

**Comment by mueller-ma** [comment]
Yes, so screenshots are shown in fdroid and description can be translated

**Comment by tibbi** [comment]
I will take a look at it someday, fdroid isnt a priority right now.

**Comment by tibbi** [comment]
fastlane things have been setup, just f-droid is having some issues lately. Guess they will properly fetch everything soon.

**Comment by mueller-ma** [comment]
Thanks
