### ISSUE TITLE
Pitfalls of "Use English" toggle

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/General-Discussion#39]
I'm personally voting against this option. It overcomplicates the app, and here's why:
- Every Android app locale has always been chosen automatically depending on system-wide setting. IMO everyone should avoid duplicating any part of this functionality.
- Given that one app has such switch, you'll need to add it to all apps. Writing so much boilerplate code in every app to implement such functionality is cumbersome.
- Moreover, translators are now confused: should they keep that option untranslated so everyone who cannot understand the currently selected locale are able to switch to English (that's the only useful application of such option), or should they translate it? The first case is unreal: how are they already using their device if they cannot understand what's going on? The latter case makes no sense, as no one would ever prefer to use app's English version while having a proper language already translated. I can't even imagine using English locale while every note is written in my native language (that's what most of people do, IMO, that's natural).

The only useful application of such toggle I can think of is being able to switch from partially translated string set to plain English one. If so, you are hiding the real issue unintentionally: a lack of translators or a lack of a well-defined translation procedure.

Please, remove the toggle. It goes against the Simple philosophy.

**Comment by tibbi** [comment]
All apps will get it eventually. Its just a couple lines, not much boilerplate at all. The real issue is obviously lack of translators, but as it is an opensource project, theres no way I can guarantee always up to date translations. There are some people who requested switching to english and it makes a whole lot of sense to me, so it will stay.
