### ISSUE TITLE
Create a Tasks app!

### ISSUE THREAD

**Issue by alpenblauwtje** [SimpleMobileTools/General-Discussion#40]
Almost every Android programming course starts with a Task app. Unfortunately and strangely there is still no Tasks app that suits my needs, not even the paid ones. My perfect Tasks app supports:
1. Tasks syncronised (based on) Google Tasks API (this makes it easy to manage tasks on multiple devices and Gmail).
2. Support for multiple Google accounts (i.e. easy switching between accounts within the app, having several widgets on the homescreen with lists of different Google accounts).
3. Multiple list support (this comes with Google Tasks)
4. Sorting mode customizable (My order, Due date, Alphabetical)
5. Support for due date/time, and a notification in the status bar if a tasks is due (note that due-time is not support by Google tasks but it is OK to have that limited per device)
6. Moving a task to another list (preferably even to another account)
7. Nice widget support
8. Material Design
9. Free and no adds, preferably open-source!

There are some nice paid apps that use their own storage instead of Google Tasks but these apps usually ask a ridiculous monthly fee (aside the question if you want to store your info at their servers. But you might ask the same question about Google storage...). 
The apps that are left usually are dropped because of requirement #1. The major apps that then remain are: Tasks (from Team Tasks), GTasks (from Appest), Astrid Tasks (open source). Tasks from VRProductiveApps is a promising new kid on the block. 
Astrid Tasks has a weird color scheme, is feature bloated and is not designed according Material Design. 
Tasks and GTasks have ads. Both have paid versions but still they aren't perfect. GTasks has ugly widgets and active development in fact stopped when Appest took over after which it begun to push their own task app TickTick.
That leaves the paid version of Tasks. Tasks is not based on Material Design and active development ended in 2013, and in 2015 it stopped working for several months. For some reason it started working again.

So, I think it's time for an open source Tasks replacement! :-)

**Comment by tibbi** [comment]
Heh, thats a long report. Tasks will someday be part of the Calendar, so Ill link this to the issue report there https://github.com/SimpleMobileTools/Simple-Calendar/issues/60 . Thanks

**Comment by alpenblauwtje** [comment]
Major tasks apps like Todoist, Any.do, Tasks, Wunderlist, etc. serve only one purpose: tasks. 
I really can imagine you don't have the time (or inspiration :)) to start another app, but I hope it will not be part of the calendar app, then you perhaps shouldn't start with it at all...

**Comment by tibbi** [comment]
Im definitely not going to do any advanced standalone Tasks app with cloud synchronization etc. We will see how will it look like in the future, for now I see it as a part of the calendar.

**Comment by MisterY** [comment]
Tasks can be integrated using existing tasks apps, like OpenTasks or Tasks.org. For example, aCalendar supports OpenTasks as the content provider.

DAVx5 supports both of the task apps above as the sync target. You could use the existing parts of the ecosystem and integrate tasks into the calendar view.
