### ISSUE TITLE
Touch feedback is invisible/hard to see on darker themes.

### ISSUE THREAD

**Issue by tttom64** [SimpleMobileTools/General-Discussion#41]
On the default light theme, touching a button will create that material ink effect, which is clearly visible. On the default dark theme, this is only visible when watching closely, and on darker custom themes, it's totally invisible. 

I don't know what the best solution to this is, as I'm not familiar with either material design or the simple philosophy. However, my suggestion is just to make the color of the feedback the same as the text color, or at least derived from it in some way. Alternatively, you could just switch between a light and dark color depending on the background colour.

**Comment by tibbi** [comment]
the default theme has been changed to dark recently, so the ripple effect can be seen better already. Not at the menu items, but in the app settings etc.
