### ISSUE TITLE
F-Droid is missing updates

### ISSUE THREAD

**Issue by mako2580** [SimpleMobileTools/General-Discussion#42]
Hi,
I know that is not your fault, but some of your apps cannot be build in F-Droid and that results that there are old versions. And now since you released version 3.0.0, it's a pity, that it's not on F-Droid.

Thanks in advance

**Comment by tibbi** [comment]
ye Ill check if I can do anything one day, f-droid seems to be really failing lately

**Comment by tibbi** [comment]
looks like they are updating it properly already
