### ISSUE TITLE
A suggestion for improving primary color selection

### ISSUE THREAD

**Issue by tttom64** [SimpleMobileTools/General-Discussion#44]
In versions 3.x of most apps, the primary color selection dialogue has changed. Evidently, it is now easier and faster to select colours.

However, this has removed the ability to choose non-material design colors. I see it as important for us to be able to change this to whatever we want. For example, prior to these updates, I used #458588 as my primary color.

I suggest:

- a button allowing the user to type in their preferred hex color code, or:
-  allow the user to double-tap the hex color code to edit it.

**Comment by tibbi** [comment]
Hey, the palette has been limited for technical reasons. If you pick any custom color, I cannot apply it to the whole app and not all colors would change. For example at the overscroll effect or the Header of the app at Recents view was still the old Orange, I just couldnt change it. Now it works in a way that theres like 180 premade styles, which apply the selected color properly everywhere.
