### ISSUE TITLE
Add pictures for F-droid

### ISSUE THREAD

**Issue by blacklight447** [SimpleMobileTools/General-Discussion#46]
Since F-droid 1.0, it is now possible to have screenshots displayed of the apps in the repos, I think it would be a good idea to add them to your repo so they can be included in F-droid.
Below you can see some examples of two apps which have already implemented this.

This is Courier:
![whatsapp image 2017-12-19 at 10 18 12 am 1](https://user-images.githubusercontent.com/19261543/34149671-1faed2fe-e4a6-11e7-9c86-2d4738795335.jpeg)
This is Orbot:
![whatsapp image 2017-12-19 at 10 18 12 am](https://user-images.githubusercontent.com/19261543/34149681-250af660-e4a6-11e7-89f0-f2bcf2733ccd.jpeg)

This way, people can have an idea of how the app looks. This will also be a good idea for your other apps, but I will only open an issue here for now so the discussion only has take place, what do you think?

**Comment by blacklight447** [comment]
P.s. I would be happy to provide the screenshots of all the apps if needed/wanted.

**Comment by tibbi** [comment]
Sure, that would help. Make them something like https://github.com/SimpleMobileTools/Simple-Gallery/tree/master/screenshots , with the navigation bar visible too, if you have such device. If not, it's not a problem. Create some for the gallery first to see how they look like, we will see if it's ok :) Thanks

**Comment by blacklight447** [comment]
@tibbi Sure, I try filling up my gallary with pretty pictures first, so they look better.

**Comment by tibbi** [comment]
thats my biggest issue too :D adding nice images, folder names, or calendar events/notes/etc in the other apps.

**Comment by tibbi** [comment]
Screenshots have been updated and also fastlane is setup so f-droid can fetch them. F-droid seems to have some issues lately, but I guess they will be added sooner or later.
