### ISSUE TITLE
Dark background for both app and actionbar

### ISSUE THREAD

**Issue by ihateregs** [SimpleMobileTools/General-Discussion#48]
Right now the only way to make this is to select dark "background" and "primary" colors, but primary color also used for switches in settings and text selecting in notes, so it covers the background and the content color the same time. Having light actionbar with dark content background is a bit annoying.

**Comment by tibbi** [comment]
There is already a new "Black & White" theme for that purpose, it has special handling. For now it is available only in the gallery, you can test how it works. It will eventually get to every app once I update them.

**Comment by ihateregs** [comment]
Yes, but it's black and white, so there is no possibility to have this with like dark gray background.If there is alredy implemented special handling i guess it's not that difficult to make like a checkbox for toggling it with custom themes?

**Comment by tibbi** [comment]
I dont really want to complicate it with a checkbox, only that one theme is special. Allowing the exception at any theme could again create many new issues.

**Comment by ihateregs** [comment]
Could be some other way of allowing to use it with different colors? Maybe like having separated color picker for that theme, or making it "current background & white" intead of "black & white"?

**Comment by tibbi** [comment]
I dont want to spend that much time with customization, this is more than good enough for 99% of people
