### ISSUE TITLE
Question about the right translation

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/General-Discussion#51]
I doubt I have a good understanding of what's the right meaning of these strings:

https://github.com/SimpleMobileTools/Simple-Calendar/blob/cbc5e000eb660975cb9ea90ab9d2101875f1ee3b/app/src/main/res/values/strings.xml#L107

https://github.com/SimpleMobileTools/Simple-Contacts/blob/f7a49749083ab7137b0f5de7c5713475557c36f6/app/src/main/res/values/strings.xml#L44

Should they mean "a day of year when a person turns 40, 50, another round date" or "a day of year when some important event took place, such as wedding, etc, and now it is celebrated every year"? Is the meaning in both apps the same?

Thanks.

**Comment by tibbi** [comment]
it is the second option. For example if you had a wedding on 3rd february 2017, on 3rd february 2018 you have the first anniversary
