### ISSUE TITLE
[App Request] Dialer / Phone app

### ISSUE THREAD

**Issue by TeeTeeHaa** [SimpleMobileTools/General-Discussion#52]
During January 2018 I was not able to find _any_ open source replacement for the stock Android 8 dialer called "Phone" from "Google LLC". I really would like to see a dialer being part of SimpleMobileTools for the [very same reasons](https://medium.com/@tibbi/why-did-i-create-simple-mobile-tools-f3aa22815aa4) I do use nearly all the other apps from SimpleMobileTools.

**Comment by tibbi** [comment]
it is on the roadmap, will be added someday

**Comment by TacoTheDank** [comment]
Are you close to releasing that Simple Dialer app? I'm about ready to ditch Truecaller just because of the sheer size of the thing lol (70MB) and I can't find any other good dialer/phone app that doesn't have ads. Can't wait!

**Comment by tibbi** [comment]
havent started working on it and there is a PDF viewer in front of it too, so it might still take months to get some dialer out there.

**Comment by bb1a2** [comment]
The thing is: we have more than one open source PDF viewers, so I think we need a dialer more.

Is there a to-do list or a road map of upcoming apps and features. Maybe you can get idea of what the users need. Thanks.

**Comment by tibbi** [comment]
ye you can vote on features and apps after pressing the left hand side button at https://simplemobiletools.github.io/ . PDF reader is currently winning over a dialer 125:114

**Comment by TeeTeeHaa** [comment]
Short searches on f-droid.org show:
* "pdf": 4 PDF readers, 2 PDF creators
* "dialer": Dialer2 from 2012
* "phone", "call", "dial": nothing for regular phone calls

...and I now voted on your website for a dialer.

**Comment by tibbi** [comment]
well apparently my users want a PDF viewer more, I added the voting there for a reason. All phones have a built in dialer which is good enough for most people. Both apps will come, dont worry.

**Comment by bb1a2** [comment]
Thanks.

Voted for dialer, messages and weather.

Quick question. If contacts are stored in Contacts private internal storage, is there a way for the constantly-changing contacts to be accessed by dialer/messages etc?

Thanks

**Comment by tibbi** [comment]
nope, there is no way third party apps can access those contacts. I will probably add some tricks there when Ill be working on the dialer and messenger, we will see. I know that keeping the contacts so inaccessible definitely has drawbacks. Maybe "Phone Storage" is the one most people want to use, not the totally private one.

**Comment by bb1a2** [comment]
Of course, but the private option kind has to be functional you know :)

I am interested to hear what you have in mind. This sounds like a good puzzle :)

**Comment by bb1a2** [comment]
OK, I'll start :)

Maybe it can be one app, with Dialer/Log/Contacts/Messages are activities within the app, each with a separate launcher icon. This will give them access to the same real-time database.

What if the user only wants one of them? Maybe they can be downloaded as plugins to this one "Communications" app. Or they can be disabled by default and you can enable the activity you want from within.

This also should have the benefit of reducing total APK/storage space/memory usage compared with separate apps, I think.

What do you think?

**Comment by tibbi** [comment]
Contacts, Dialer and Messenger will be whole standalone apps

**Comment by bb1a2** [comment]
I understand :)

I would just like to ask you to keep the private option in your mind when designing the apps.

Thank you for your work.

**Comment by bb1a2** [comment]
Any updates?

I happily noticed that dialer overtook pdf viewer by some margin.

**Comment by tibbi** [comment]
ye, the dialer will be the next app, but Im still not sure when :)

**Comment by bb1a2** [comment]
Thanks :)

**Comment by tibbi** [comment]
now that I started thinking of the implementation, maybe the Dialer will be just a part of Simple Contacts, as I was initially considering. I wanted to create separate apps, but the Dialer still has to display some list of contacts, favorites, filters etc, so I would have to copypaste a huge amount of code, UI and settings. One merged app would also make it easier to work with the "Phone storage (hidden from other apps)" contacts. Messenger can probably still be a separate app, we will see once I get there. It would still need some hacks to work with those totally private contacts.

**Comment by bb1a2** [comment]
Totally agree.
Call log will be part of Dialer, right?

**Comment by tibbi** [comment]
ye, of course

**Comment by hurradiegams** [comment]
> 
ye you can vote on features and apps after pressing the left hand side button at https://simplemobiletools.github.io/ . PDF reader is currently winning over a dialer 125:114
> 

I am sorry, but I can't find any left hand side button for voting, let alone said Apps (eg. Dialer).
Sorry if I'm blind, but please point me to the voting option :)

**Comment by tibbi** [comment]
![share](https://user-images.githubusercontent.com/528931/42988852-7732210c-8bfe-11e8-8d8e-2f6e390c4065.png)
you need to have javascript enabled to see it

**Comment by hurradiegams** [comment]
Aaah, thank you! :)
 
Because of my too restrictive blocking of userreport.com it didn't show up, FYI.

**Comment by TeeTeeHaa** [comment]
When using the default dialer "Phone" and the default "Contacts" (or Simplemobiletools' "Contacts") you're always hoping around between those apps - so this looks like the normal way for the user to do that.

Whether dialer and contacts are one app or different apps does not matter for me - I can envision both ways.

Before starting to plan a dialer app I highly suggest to have a look at the functionality of the default dialer - there are *a lot* of settings! My impression (as Android user, not as Android developer) is that the dialer is the most complex app in the menagerie of dialer/contacts/messages/calendar. Nevertheless I'd highly appreciate a non-Google open source dialer.

**Comment by tibbi** [comment]
Im closing this as it will be definitely a part of Contacts, it is reported at https://github.com/SimpleMobileTools/Simple-Contacts/issues/224

**Comment by endeavorz** [comment]
I wanted to also put in a plug to get a dialer from you too.\
I am trying to find that darn vote button, for browsers not only to I have IE, also I have Firefox, and Chrome, and I can see that vote button you show on your screenshot, and I have java enabled...

I want to vote my vote for a dialer over a pdf app too, but can't figure it out yet to find the little button on the left, so i will say my peace here, thanks

**Comment by tibbi** [comment]
the button has been removed, as the roadmap is pretty clear for quite some time now :) It was used only by spambots and people reportings bugs, so I didnt want to waste time with clearing and maintaining it

**Comment by TacoTheDank** [comment]
which button

**Comment by endeavorz** [comment]
ahhh I see, thank you, 
You saved me from pulling out my hair, not that I have much left LoL

...and btw, thank you for your reply to my personal email earlier today, I appreciated it !

**Comment by TacoTheDank** [comment]
ah ok
