### ISSUE TITLE
[Suggestion] Use Styles API from LineageOS for theming

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [SimpleMobileTools/General-Discussion#58]
https://lineageos.org/Introducing-the-LineageSDK/

They released a SDK a few days ago. Maybe this is something to look into in regard of theming in Simple Mobile Tools.

Best regards!

**Comment by tentacleuno** [comment]
Maybe the Simple apps need a redesign in general? They look like Android 5.0 apps IMO, and the colour scheme looks out of place.  I hope they get updated to look like modern apps at some point.

**Comment by tibbi** [comment]
automatic dark/light theme just started rolling out, so Ill close this
