### ISSUE TITLE
Java Source files for Applications 

### ISSUE THREAD

**Issue by SheikhZayed** [SimpleMobileTools/General-Discussion#6]
Hello,Thank you very much for open sourcing these great apps!all the apps which i wish to work on is developed using kotlin.please share java source code too ASAP

**Comment by tibbi** [comment]
Hello, I dont want to use java anymore, I will be moving the remaining apps to Kotlin too. Everybody should move away from java already :)

**Comment by SheikhZayed** [comment]
Please,iam still using java and want to work with your projects.migrating to kotlin wont be that easy .. please understand

**Comment by tibbi** [comment]
I understand, but I wont rewrite all apps to java just for you :) Give kotlin a try, its worth it. You have so many examples at these apps.
