### ISSUE TITLE
Add ability to set instant messaging account in contact vcard

### ISSUE THREAD

**Issue by SamWhited** [SimpleMobileTools/General-Discussion#61]
I would like to request the ability to add an instant messaging account in the vcard like the default Google contacts app.

Specifically, I would like to set the Jabber field because my text messages are delivered through XMPP (historically called Jabber) and setting this field lets my XMPP client associate contacts from the address book with the people messaging me. However, this field is useful for more than just niche things like my phone provider, it also allows you to put in other addresses and keep track of how you contact your friends on a number of platforms.

**Comment by tibbi** [comment]
ye additional fields for Contacts are on the roadmap, i cannot promise any date though. Anyway, it is already reported at https://github.com/SimpleMobileTools/Simple-Contacts/issues/90
