### ISSUE TITLE
enhancements to contacts suggestion : linking between apps

### ISSUE THREAD

**Issue by jfbertrand007** [SimpleMobileTools/General-Discussion#63]
I have noticed that phone numbers and address are not able to be clicked on to dial or show map...
also when you add a new client you have to close the contact app and re-open so to see the new entry

**Comment by tibbi** [comment]
numbers, emails and addresses should be clickable already on the view screen too, what app version do you have?

**Comment by jfbertrand007** [comment]
ooops my bad, i guess its just not click-able when you just add the new contact ...

**Comment by tibbi** [comment]
of course, it is an edit field, clicking it just moves the cursor inside. Also by that invisible new contact you mean that if you launch the app, press Plus, create a new contact and save it, it throws you back at the main screen, but the new contact is invisible? Then if you reopen the app without changing anything it is visible already?

**Comment by jfbertrand007** [comment]
yes that is about right ... but it seems fixed now ... 
when i add a new contact it's usually because i want to call the person of view its address on the map... but when i save it get me back to the main list then i need to search the contact and click the phone or address... anyway seems like maybe i need to change how i input things ...
thank
jf

**Comment by tibbi** [comment]
well that is expected, I dont plan changing it right now
