### ISSUE TITLE
Cannot run simple calendar in an api-27 emulator

### ISSUE THREAD

**Issue by touchrank** [SimpleMobileTools/General-Discussion#67]
Component class com.simplemobiletools.calendar.activities.SplashActivity.Red does not exist in com.simplemobiletools.calendar.debug

**Comment by tibbi** [comment]
ye colors will be added soon, I havent commited some work in progress

**Comment by tibbi** [comment]
I added try/catch blocks in commons 3.21.5 so it shouldnt crash anymore. The apps are usually in runnable state, Im just waiting for new icons longer than I expected.
