### ISSUE TITLE
Ongoing notification in clock to prevent it from being killed

### ISSUE THREAD

**Issue by andreas951207** [SimpleMobileTools/General-Discussion#68]
In some ROM's background apps will be killed by the system.

The solution is that there is always a running notification. This could be turned on/off in settings.

It is very important for a alarm clock.

Thanks! Love all simple apps.

**Comment by tibbi** [comment]
moved it to Clock repository, duplicate of https://github.com/SimpleMobileTools/Simple-Clock/issues/52
