### ISSUE TITLE
Please make a web browser

### ISSUE THREAD

**Issue by esmoak** [SimpleMobileTools/General-Discussion#71]
Specifically a fork of Lightning.

It would be great to have a browser similar to Lightning but with a JavaScript and image quick toggle button on the toolbar.

See: https://github.com/anthonycr/Lightning-Browser/issues/693

When I want super fast browsing, I keep JavaScript and images off until needed. It's safer to browse with JavaScript off anyway, but it is needed for some sites.

Thanks. I'm a huge fan of your work. Amazing developer.

It would be a bonus is it had separate site settings as an option kinda like F(L)OSS or Privacy Browser.

**Comment by paramjitrohits** [comment]
Hello, please have a look at Privacy Browser (available on F-Droid and play store).

**Comment by esmoak** [comment]
@paramjitrohits Privacy Browser doesn't have tabbed browsing and it still seems far away from happening.

FOSS is still a little clunky.

I know tibbi could excel in making a webview browser, although I admit there isn't a real big hole to fill in the current offerings.

A Chromium based one would be super impressive, too, but from the problems Bromite has encountered, it seems it's hard to get one on F-Droid.

**Comment by genodeftest** [comment]
Why not using Firefox mobile and disable JavaScript?

**Comment by esmoak** [comment]
@genodeftest Firefox, Fennec, etc, are slow on my device. Also, I like to selectively enable javascript when needed. So a toggle option is nice.

**Comment by test2a** [comment]
isn't Firefox focus just the right thing for the job?

**Comment by genodeftest** [comment]
@esmoak As the current versions of Firefox are the fastest browser out there, you probably won't get any faster browser. Creating and maintaining a separate rendering engine is just not feasible so you'd need to use Blink (Chrome), Gecko/Servo (Firefox) or WebKit (Safari). Also, expect massive performance improvement in Firefox when the merge of servo is completed. This happens in incremental steps starting about 1 year ago and lasting at least another year.

A toggle option for JavaScript could be implemented in an Addon such as NoScript or [this simple toggle button extension](https://addons.mozilla.org/en-US/firefox/addon/javascript-toggler/). No need to reinvent the wheel.

**Comment by pthfdr-42** [comment]
They have said WebView. You should not force the user to install 2 applications that do the same thing.

**Comment by genodeftest** [comment]
I recommend against implementing a browser. This is extremely much work to do it right or it will be broken or insecure.

**Comment by esmoak** [comment]
Going to close issue unless the developer wants to reopen.

A the time, I was really hoping for simple webview browser, but I honestly think their are better and more secure options available.

Really, a fork of Firefox would be cool, but a browser probably doesn’t fit in with Simple Mobile Tools in general.

Chalk this issue up to me naive.
