### ISSUE TITLE
Consider adding another donate option

### ISSUE THREAD

**Issue by esmoak** [SimpleMobileTools/General-Discussion#72]
On: https://simplemobiletools.github.io/donate/

It would be nice to have another donate option. 

I know Blokada, and probably other apps, use: https://donorbox.org/

If you don't like donorbox there might be another service which makes it easy to donate with a credit card. 

Your paid "Simple Thank You" is a nice option except for those of us who don't want to use the Play Store.

Thanks for all you do.

**Comment by tibbi** [comment]
donorbox is for nonprofits
