### ISSUE TITLE
Simple Clock is missing from your Google Play Banner

### ISSUE THREAD

**Issue by TacoTheDank** [SimpleMobileTools/General-Discussion#73]
![screenshot_2018-05-26-18-44-07](https://user-images.githubusercontent.com/32376686/40581703-606d49ca-612d-11e8-9947-790cc8915604.png)

also it's slightly off-center

**Comment by tibbi** [comment]
ye more apps are missing from there and it is hard to scale it properly, as always a different part of it is shown in different cases :/ Ill get there someday.

**Comment by TacoTheDank** [comment]
hopefully lol
