### ISSUE TITLE
Simple Login, Register and Forgot Password 

### ISSUE THREAD

**Issue by pkgulati** [SimpleMobileTools/General-Discussion#77]
How about a new app, having Simple Login, Register and Forgot Password UI

**Comment by tibbi** [comment]
login, register where?

**Comment by pkgulati** [comment]
Mainly it should be just UI, so people should be able to configure URL for server on their own, so it is like a UI template, just like [this one](https://github.com/sirvar/robin) but what I wanted was consistency in theme, and code like all other simple apps you have created.

**Comment by tibbi** [comment]
sorry, but I dont really see any sense in such app
