### ISSUE TITLE
Messaging app with private storage

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/General-Discussion#81]
Hi,

I wish you would consider doing the messaging app next, with private storage.

Reasons:
- To complete Communications suite: Contacts, caller, dialer, messages.
    - People who like an app are likely to search for other apps from the same developer.
    - To break away from Google apps to apps that are integrated/ behave the same between them.
    - Private storage of all three is a great USP.
- No FLOSS app I know of offers private storage of messages.
- There are many FLOSS PDF apps.

Thanks for consideration.

**Comment by tibbi** [comment]
I dont plan creating that, there are a million alternatives already

**Comment by bb1a2** [comment]
There are alternatives but do you know of any with private storage? Real question.

I respect your decision and can't emphasize how grateful I am for your work. Just let us know if you ever reconsider.

Thank you :)

**Comment by tibbi** [comment]
not sure what you mean by private storage. For example https://play.google.com/store/apps/details?id=com.radicalapps.cyberdust&hl=en doesnt even store them on any hard drive whatsoever, messages exist only in memory. Anyway those apps are really difficult, online, so they dont fit into the concept at all.

**Comment by bb1a2** [comment]
I mean store SMS messages in the app's own storage like you do with Contacts. This way apps that must have SMS permissions can't access them.

**Comment by tibbi** [comment]
aha, I didnt know it is about SMS. Anyway I dont think that is doable that easily.

**Comment by bb1a2** [comment]
I believe in you! :)

Considering the reasons in post 1, I think it is worth it.

Thanks
