### ISSUE TITLE
An idea for sharing contacts privately among apps

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/General-Discussion#82]
- Using an file in a location accessible to all apps.
- The user provides a password through Contacts to create and encrypt the file.
- The user provides the same password through the other apps to decrypt the file and copy the database to their internal app storage.
- If the user, for example, adds a contact, the database gets updated accordingly.
- The file modification date/time are read on app launch/periodically/on user request/real-time monitored/etc. If different, the database in the file is imported and updated within the app.

This provides real-time updates across your apps (Contacts, SMS, Calendar, etc) that have the password without letting other apps access the database.

What do you think?

**Comment by tibbi** [comment]
Ill close this as it is way out of the scope of the apps. You can already share privately stored contacts via Simple Contacts Pro, some apps within our suite will see them.
