### ISSUE TITLE
App icon color customization doesn't work with some launchers

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/General-Discussion#83]

**Comment by Grammost** [comment]
I have a similiar issue with Trebuchet Launcher, LineageOS 15.1, Android 8.1.
Strangely enough, the app icon colors only won't change when I use the default icon pack. When I use a custom icon pack (like Ameixa) the icon colors are shown properly.

**Comment by 0pLuS0** [comment]
I'm playing with Nova and it works fine with it...

**Comment by ouzowtf** [comment]
It doesn't work with the latest Nova beta for me, as already stated in another issue.

**Comment by tibbi** [comment]
ye it seems to be an issue with the Beta version of Nova Launcher. I reported it, we will see what will they do about it.

**Comment by 0pLuS0** [comment]
Off Subject here, I noticed Yalp Store shows updated versions quicker then F-Droid.

I was on yesterday and Yalp Store listed a new update for one of your apps, but it wasn't listed on F-Droid, that's quite bothersome, that F-Droid is slow like this...

I'd contact them and tell them as a developer you'd appreciate it if your updates were put out the same time Yalp Store seems to make it happen...

hmm

**Comment by tibbi** [comment]
That doesn't belong to this issue at all, open a new one if you want.
Anyway, seems like Nova 6 broke it intentionally and don't want to fix it, you can support my issue at https://plus.google.com/u/0/+TiborKaputa/posts/VUvW4ZmiSpG .

**Comment by mohriza** [comment]
saya memiliki masalah layanan kostumisasi tidak berjalan sesuai mohon bantuannya terima kasih

**Comment by Termuellinator** [comment]
For Reference: i created https://jira.lineageos.org/browse/BUGBASH-2348 to let the LOS-devs know about this.

**Comment by tibbi** [comment]
I would avoid telling that it affects "only" Trebuchet and Nova Launcher, as it occurs to some other less popular ones too.

**Comment by ouzowtf** [comment]
Works again with Nova Launcher version 6.1.3

**Comment by tibbi** [comment]
thats good to hear, thanks :)

**Comment by tibbi** [comment]
we apparently cannot do anything to fix this on our side
