### ISSUE TITLE
Add option to suppress "fake version of app" in commons library

### ISSUE THREAD

**Issue by sagarsiddhpura** [SimpleMobileTools/General-Discussion#85]
For some of us who want to use commons library or who are using fork of any simple app, it would be helpful if you could provide a way to suppress this dialog. 

I understand the need to stop clone-repo-publish-app apps who want to prosper on efforts of simple tools. But at same time some of us use apps and make significant changes and publish. Some of us enjoy the benefits of opensource apps and also contribute further by publishing own apps also opensource. Some of us clearly menton in the app that is possible because of original app and link to it.

Can I request a way to skip that dialog. Maybe setting some gradle property or init a variable in activity or setting some variable in App class?

**Comment by tibbi** [comment]
I dont want to remove that. You are not supposed to use Commons directly. If you need some function just check how it works and copy it over, do not just call something you dont understand.
