### ISSUE TITLE
[new app idea] Simple SMS

### ISSUE THREAD

**Issue by petermolnar** [SimpleMobileTools/General-Discussion#87]
With Google re-branding and forcing Google things in the former AOSP messages - not just the dialer - the only open source messaging alternative right now is QKSMS. While it's a neat software, it's a teeny bit too heavy since 3.x and 2.x is surprisingly buggy. 

There's definitely room for a simple, reliable, independent, open source SMS application. It could even be pure sms, no MMS or anything.

**Comment by tibbi** [comment]
it has already been reported, but thanks
