### ISSUE TITLE
Add a PDF viewer

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/General-Discussion#9]

**Comment by KrasnayaPloshchad** [comment]
This could be created based on MuPDF.

**Comment by Jazcafe** [comment]
+1 👍 

This would be great.  There are a lot of free PDF readers but none that follow the 'Simple' philosophy 😄

**Comment by F3000** [comment]
Is here any progress ?

**Comment by tibbi** [comment]
it is the next app on the roadmap, but I want to improve the current ones a bit first

**Comment by F3000** [comment]
In which way do you implement this ? Standalone app or over filepicker in the file manager ?

**Comment by tibbi** [comment]
a standalone app as it will open a couple other formats too, not just pdf. Some more general document viewer and an e-book reader.

**Comment by F3000** [comment]
ok when you release a seperate app is good. When you have released this i will come to you with some wishes :)
Can we expect the app in first half of 2018 ?

**Comment by tibbi** [comment]
most likely ye, some initial version could be released within a couple months, we will see.

**Comment by NikhilSudhakaranVG** [comment]
No progress after 10 months???

**Comment by tibbi** [comment]
actually no, I want to focus on the existing apps for now

**Comment by Sytten** [comment]
Any progress, I would pay for this the moment it gets out.

**Comment by Aga-C** [comment]
@tibbi It would be a great idea to release a simple PDF viewer. Currently, there is no open source reasonable application that has also a search functionality (for me this is the most important feature) and clean & neat user interface.

**Comment by KrasnayaPloshchad** [comment]
Google have released the Google PDF Viewer, so what happened if you make use of that as backend?

**Comment by tibbi** [comment]
has been added to the file manager
