### ISSUE TITLE
Will apps stay open source?

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/General-Discussion#97]
Will the apps continue to be open source with the recent releases of paid Pro versions and deprecation of free ones? Will anything be available on F-Droid for free?

**Comment by tibbi** [comment]
ye, I described everything at https://medium.com/@tibbi/some-simple-mobile-tools-apps-are-becoming-paid-d053268f0fb2 . Pro apps will be new apps on f-droid too, people will have to redownload them, not just update.

**Comment by trubitsyn** [comment]
Thank you!
