### ISSUE TITLE
Simple Calendar Pro version

### ISSUE THREAD

**Issue by ema-pe** [SimpleMobileTools/General-Discussion#99]
Hi,

I'm a user of Simple Calendar, and I read the blog post about the plan to switch all applications to a paid version. But I didn't understand only a thing: I downloaded  and keep updated Simple Calendar through F-Droid, but the application on this store isn't updated as the Google Play Store version (that is now the "pro" version). Does it will be updated?

**Comment by tibbi** [comment]
the pro calendar has just been released on google play. F-droid has no pro apps yet, I will get to that within the next few days.

**Comment by ema-pe** [comment]
@tibbi thank for the clarification, but the enforced pop up is really annoying.

**Comment by tibbi** [comment]
it should be showing up just once actually, I just found the glitch which makes it always appear.
